### ISSUE TITLE
Vnc server automatically stops after 15-20 seconds

### ISSUE THREAD

**Issue by Rea-l79** [RandomCoderOrg/ubuntu-on-android#100]
After starting Server, the VNC connection will lost about each 15~20 seconds.  At this moment, If I touch the termux application on the screen of the phone, the connection might come back to work for a next 15~20 seconds, and then, lost again.

**Comment by SaicharanKandukuri** [comment]
probably insufficient ram
or android killing it as of Battery Optimisation

> follow this documentation from termux to enable wake-lock
this could solve your problem

- https://wiki.termux.com/wiki/Termux-wake-lock

###### using [termux-x11](https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui/termux-x11) is good for now

**Comment by Rea-l79** [comment]
No it is not working after 15-20 seconds vnc viewer stop responding and I have to open termux again and then just go back to vnc viewer and then again it stops responding.
Device- Realme 6pro 6gb ram

**Comment by rrkrudra** [comment]
vnc server starting with blackscreen and cursor

**Comment by SaicharanKandukuri** [comment]
yep cause udroid become heavy in vnc!

**Comment by SaicharanKandukuri** [comment]
@Rea-l79 
@rrkrudra 

check out this blog
https://wmcbtech30.github.io/posts/android-daemonized-process/

**Comment by MrHomebrew** [comment]
To make it easier for users maybe add instructions for this on the main page.

**Comment by SaicharanKandukuri** [comment]
> To make it easier for users maybe add instructions for this on the main page.

for now it stays in issue
