### ISSUE TITLE
Under Home everything is read only

### ISSUE THREAD

**Issue by v8karlo** [RandomCoderOrg/ubuntu-on-android#108]
Samsung S20 5G. I installed Udroid through DEX and had issues with Vnc Viewer.
Switched to BVnc and Udroid worked. DEX could not start Vnc Viewer because it is made only for touch controls. BVnc worked like charm.
Under Home dir everything was read only and could not create dir or copy/move files (I did run termux-setup-storage and granted storage access to termux in app/termux)
I could access phone internal memory and have full read/write access to it, but Home not.
In effort to gain access to Home folder i apt purge xfce4 and installed superuser su - karlo (me).
Under (karlo) sudo installed ubuntu-mate-desktop.

I was following instructions from YT user how to install MATE, partially, and I used it to install MATE on Udroid installation with superuser.
Removed XFCE4 (it made conflicts in tigervncserver when MATE is installed).
Without XFCE4 tigervncserver acted normally and MATE desktop worked like charm.
https://www.youtube.com/watch?v=QDyBXIrt52s

tigervncserver -xstartup /usr/bin/mate-session -geometry 1920x1080. (start session)
tigervncserver -kill (after session ends )

And everything started to work. Gain full access to my HOME/ folder and internal memory of phone under MATE desktop. 
Instaled Monodevelop (works), Office, Gimp works and all other software from MATE works just fine.
Sound works fine.
System is stable even after week of intense testing. After tweaking with MATE it looks better than most of the desktops I ever saw.

Great work you did with Udroid pkg! 
It is huge obstacle why chroot can not access phone gpu, but combining Ubuntu and DEX works for me.
Ubuntu and DEX overlaps without any issues and can use both softwares like it is single operating system.
Copy/Paste works beetwen DEX-android and Ubuntu.

Udroid is not crashing and is stable under MATE desktop and I installed tons of software in MATE for testing.  

You did great work with Udroid.
Hope that someday Termux/Udroid will be able to gain access to phone GPU, then the work would be completely and absolutely perfect!
And if udroid can access external disk attached to my phone (have a hub for attaching devices and charger) that would be the day! But for that I use DEX apps. It is enough that Udroid can reach my phone internal storage so I can pass data that way from Ubuntu.

Whoever has phone with DEX (usb 3.0 upwards) my recomendation is to install Termux and ubuntu through DEX and use them both as single operating system. 
It works so good that I have real laptop capabilities. 
It is amazing how good it works!

Many thanks, exceptional work !!!
Karlo.

**Comment by SaicharanKandukuri** [comment]
> Samsung S20 5G. I installed Udroid through DEX and had issues with Vnc Viewer. Switched to BVnc and Udroid worked. DEX could not start Vnc Viewer because it is made only for touch controls. BVnc worked like charm. Under Home dir everything was read only and could not create dir or copy/move files (I did run termux-setup-storage and granted storage access to termux in app/termux) I could access phone internal memory and have full read/write access to it, but Home not. In effort to gain access to Home folder i apt purge xfce4 and installed superuser su - karlo (me). Under (karlo) sudo installed ubuntu-mate-desktop.
> 
> I was following instructions from YT user how to install MATE, partially, and I used it to install MATE on Udroid installation with superuser. Removed XFCE4 (it made conflicts in tigervncserver when MATE is installed). Without XFCE4 tigervncserver acted normally and MATE desktop worked like charm. https://www.youtube.com/watch?v=QDyBXIrt52s
> 
> tigervncserver -xstartup /usr/bin/mate-session -geometry 1920x1080. (start session) tigervncserver -kill (after session ends )
> 
> And everything started to work. Gain full access to my HOME/ folder and internal memory of phone under MATE desktop. Instaled Monodevelop (works), Office, Gimp works and all other software from MATE works just fine. Sound works fine. System is stable even after week of intense testing. After tweaking with MATE it looks better than most of the desktops I ever saw.
> 
> Great work you did with Udroid pkg! It is huge obstacle why chroot can not access phone gpu, but combining Ubuntu and DEX works for me. Ubuntu and DEX overlaps without any issues and can use both softwares like it is single operating system. Copy/Paste works beetwen DEX-android and Ubuntu.
> 
> Udroid is not crashing and is stable under MATE desktop and I installed tons of software in MATE for testing.
> 
> You did great work with Udroid. Hope that someday Termux/Udroid will be able to gain access to phone GPU, then the work would be completely and absolutely perfect! And if udroid can access external disk attached to my phone (have a hub for attaching devices and charger) that would be the day! But for that I use DEX apps. It is enough that Udroid can reach my phone internal storage so I can pass data that way from Ubuntu.
> 
> Whoever has phone with DEX (usb 3.0 upwards) my recomendation is to install Termux and ubuntu through DEX and use them both as single operating system. It works so good that I have real laptop capabilities. It is amazing how good it works!
> 
> Many thanks, exceptional work !!! Karlo.

Thanks @v8karlo Iam happy to hear that

###### homedir problem!
Try this command 
```bash
chown -R $(whoami):$(whoami) ~
chmod -R +r+w ~/*
```
> Gets fixed in stable versions of udroid v3 ✌️

###### GPU acceleration in udroid & all other termux proot distros 
It still a long way to come. Dev's around termux community working hard to figure out ways to accomplish!
> For now termux-x11 app gives a small taste of smoothness

Again 
Thanks!

**Comment by v8karlo** [comment]
Thank you for a quick response!

I am interested in termux-x11 and followed instructions from
https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui/termux-x11

(My termux if from F-droid and is 97Mb instalation, and in it I have installed Udroid and Mate working.)

Downloaded Termux_debug 0.118 and installed
Downloaded app_debug.apk (termux-x11)

MY Termux changed and now have debug capabilities.
I set the log level to debug in its properties (android apps).

pkg install x11-repo -y
pkg install xwayland termux-x11
// both packages installed

echo 'allow-external-apps = true' >> ~/.termux/termux.properties
// ok

// in ternux execute - error
termux-x11

Termux:X11 is not installed

apt install termux-x11
termux-x11 is already the newest versio (1.0.4)
-------------------------------------------------
proot-distro login udroid --shared-tmp
// ok - I am root now

-------------------------------------------------
export DISPLAY=:0
// error - no such file or directory

dbus-launch --exit-with-session mate-session
// error
// unable to init server
// 17:30:18:817; Can not open display

My question is:
Do I have to remove Termux F-droid installation first and then install only Termux-debug version which is only 20+Mb?
I installed Termux-debug over F-droid Termux!
Is that the problem?  (on that Termux-F-Droid setup I already have ubuntu Mate which will be lost)

Or the problem lies elsewhere?

Once again I followed instructions from:
https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui/termux-x11

Thank you in advance!

**Comment by SaicharanKandukuri** [comment]
`termux-x11` launcher as installer package insider `termux-x11` zip file which you downloaded.

just need to install
 `dpkg -i /path/to/file` in termux session 
it should work

& `export DISPLAY=:0` is not supposed to give error (No such file or directory ) unless some other argument is set while logging in

About Termux App.
yes you should install a dev build of it cause termux-x11 is not officially released yet   

as suggested in the documentation
> Termux dev build from Github actions
> termux-x11 app from Github actions


Official f-droid version cause permission issues & termux-x11 cant access termux filesystem for checking permissions

**Comment by v8karlo** [comment]
There was another termux-x11 which is different from that one inside archive, which results always in error.
Now everything passes, but after execution of termux-x11 , termux stops and terminate itself.
Will look into it. But now it does what was supposed to.

Another question in mind!?

Why bother to find a way for proot to see GPU?
I asked my friend on work (I am 25+ C# programmer / Win) can I port existing C#/Java/C++ apps to android?
The answer was: Yea, but the problem is how to adapt all the mouse/keyboard functions to touch?
I said: Well, that is exactly what I need. A desktop applications ported to android for use with Samsung DEX,
with support of GPU, mouse and keyboard, I am not interested in touch support for apps I have in mind!
I don't need mobile apps, but full screen desktop apps which can use CPU/GPU/mouse/keyboard full support as android apps.

Linux is open source community and source code is available. Why not to port existing linux apps to android?
Why bother to crack proot for GPU when all major apps can be ported as android apps which utilize GPU without problems?

**What do you think about that?**

Google have Google apps store!
Linux can have Linux desktop store!

Samsung DEX already exists as launcher for desktop apps!

You don't need Samsung s21+ which is expensive, buy older S9 (have DEX) for peanuts,
and have mobile phone and desktop support machine!


I installed Firefox for android, it is pale version of full desktop Firefox.
They rather made android crap version than ported full desktop power Firefox?
Is that stupid, or what?

Samsung DEX is a solution as launcher, just need to use it properly!
Full CPU/GPU/mouse/keyboard support at palm of a hand! And much more.

In future DEX will be available on middle class phones, it already started.
Samsung A90 has DEX support, it is not S class but A class (middle class phone).
Few years from now DEX will be in every Samsung phone, probably.

And that is the way we should follow.
In time develop DEX addons to look or feel as linux desktops.
This is how it starts, with small things, until it gets its own wings.

Anyway android behaves as linux. Linux users can continue on DEX just as on XFCE?
There is no much difference!

You tell me!

**Comment by SaicharanKandukuri** [comment]
Yes, it is possible to port Gnome or any other software to android OS cause they are opensource, but all of them follow traditional Linux implementation ( like fs hierarchy, `systemd` Implementations ) and every library need to be recoded to satisfy android Implementation and be able to work in SElinux implementations which dramatically increases the scale of porting!
> `termux-app` is the best example of this they are doing their best in porting so many libs to android


and proot is never meant to be perfect cause its a hack that uses `ptrace()` kernel implementation  to make the environment look like a traditional Linux ( this caused so many applications to work )

GUI acceleration is possible in proot. the best example is `Xservel-xsdl` and `termux-x11` apps. with some effort, people and time it gets better and better

Even if you port Gnome to android with so much effort for sake of usage you may need to port all applications too ( or there is no use in watching gnome empty )
> Even Samsung dex had an app called LOD ( Linux on Dex ) which uses lxc containers to run ubuntu in android but they closed that project. ( for so many reasons like they had to modify kernel for every device to satisfy linux ) 


Android was never meant to be a better development environment ( instead it aims to be a better platform for seeking content )
so if there is anyone that could bring a better secure Linux environment that would-be creators of android leave a better gap in their OS to pass in. and all other developers and organizations showing interest to port their applications

for now, `termux org` and some other developers  are the only people doing efforts to make this a better place
