### ISSUE TITLE
Please update to Ubuntu 21.10 (or 22.04 LTS)

### ISSUE THREAD

**Issue by inari-codes** [RandomCoderOrg/ubuntu-on-android#109]
The support for Ubuntu 21.04 has ended 5 days ago at the time I'm writing this. 

Could you please update to a newer version if you can.

**Comment by SaicharanKandukuri** [comment]
Ubuntu 21.10 & ubuntu 22.04 already released!

But
Ubuntu 21.10 as beta release
Ubuntu 22.04 in fs-cook repo

> Need to install them manually

**Comment by inari-codes** [comment]
uh okay, I forgot there is a beta testing version
