### ISSUE TITLE
[Process completed (signal 9) - press Enter]

### ISSUE THREAD

**Issue by v8karlo** [RandomCoderOrg/ubuntu-on-android#110]
I installed udroid v3 xfce and it looks nice. 
Using vnc as output. 

Today I had phone update and now updated to Android 12 UI 4.0

And guess what? 

Android keeps terminating Termux
[Process completed (signal 9) - press Enter]

It is Android related thing with
max_phantom_processes limited to 32

And I am unable to use Termux any time soon on my phone! 
Not only me, anyone who upgrade to Android 12 won't be able to use Termux! 

The whole article can be read here:
https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8#commands-to-disable-phantom-process-killing-and-tldr

If anyone have solution or can help, please do so! 

I like the udroidV3! 

Please help!

**Comment by SaicharanKandukuri** [comment]
for now, I don't have any android 12 devices to recreate this issue
I'll try to test this in virtual android 12 env

**Comment by v8karlo** [comment]
Thank you in advance! 

I can start vnc and start udroid, but it is matter of seconds when android kicks in and kill Termux. 

So, I can start udroid v3 for a minute or max 2 min (yesterday) and then Android shuts me down.
As I can see, I am not the only one, all who upgraded to A12 have that issue with A12 and termux. 
https://github.com/termux/termux-app/issues/2366
(They are trying to kill Linux community, there is no money in free software, but I and many others paid for phone and can install on it what ever we want. It is criminal violation of user rights. They criplle our phones and render them uselles.) 

Anyway, udroid v3 looks nice. I could not test it longer than 2 min., but first look 5+, like it very much! Great work! 

Thanks!

**Comment by SaicharanKandukuri** [comment]
Thanks, @v8karlo 

for now, I can't do anything cause I can't run udroid in the android emulator and ONE UI 4.0 for my device releases this year may

also, `PhantomProcessRecord` is acting a bit weird in my VM 
sometimes it kills at ~40 child processes and sometimes it won't do anything even for 400+ processes 
![image](https://user-images.githubusercontent.com/68287637/151345648-2456e8e5-203c-441c-b488-285c8ae504fe.png)

> (They are trying to kill Linux community, there is no money in free software, but I and many others paid for phone and can install on it what ever we want. It is criminal violation of user rights. They criplle our phones and render them useless.)

Don't worry this is soo new to everyone I guess solutions come soon!
OpenSource projects find its way soon✌️

**Comment by v8karlo** [comment]
My regards to you! 
Keep doing excellent work on Udroid! 

Karlo!

**Comment by v8karlo** [comment]
SOLUTION for Android 12 users

It is not only termux affected with it, but lots of other apps from third party's and play store, and programmers don't have a clue why their apps won't work anymore and spending lots of time in debugging their apps not knowing that it is not their fault leaving them with apps which don't work with Android 12 update. 
Great damage is done to that programmers which must rewrite their software in order to function with Android 12 update. 
So, it is actually virus! 
It is impossible to code right because phantom process killing can kill their app without warning any time. 

You can follow debate over this virus? On the page
https://issuetracker.google.com/u/0/issues/205156966#comment37


Page where it is explained how to disable it by trick

https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8#commands-to-disable-phantom-process-killing-and-tldr


Phantom process killing has initial setting of 32. Goal is to set it for max processes Max INT 2147483647, which it will never reach, you won't disable it but cheat it! 

Start adb shell over the PC or wifi 

Disable phantom process killing

adb shell "/system/bin/device_config put activity_manager max_phantom_processes 2147483647"

adb shell "/system/bin/device_config set_sync_disabled_for_tests persistent; /system/bin/device_config put activity_manager max_phantom_processes 2147483647"

------------------------------------------------------------------------

Re-enable device config sync - before next update on phone, it is unknown will it conflict with the updating phone so re-enable before updating phone

adb shell "/system/bin/device_config set_sync_disabled_for_tests none"

------------------------------------------------------------------------

Check device config sync mode stored in settings

adb shell "/system/bin/settings get global device_config_sync_disabled"

**Comment by v8karlo** [comment]
After  disabling phantom process killing termux works just fine and I am using Ubuntu as usual. 

V3 looks pretty good, but I am still using V2 because of stabillity. 


Good work., hope you continue with this amazing project!

**Comment by SaicharanKandukuri** [comment]
for now, I am busy with a lot of external works
V3 stable may take more time
but beta filesystem gets updated frequently with new fixes
> like udroid mate beta v2

**Comment by v8karlo** [comment]
You are doing great job! 

Karlo!

**Comment by v8karlo** [comment]
With the phantom process killing they are actually targeting people like us, intentionally! 

They don't wanna see Linux or similar on phones and will try to disable projects like this. 
There is no money in Linux for them! 

But selling apps over play store is the way for them to go.

**Comment by v8karlo** [comment]
I just love this project and I am using Ubuntu on phone a lot! 

Combining Samsung DEX and Linux udroid is very powerful, and I didn't use my laptop for over 2 months now. Didn't needed it. Have everything on my phone! 

Just amazing!

**Comment by SaicharanKandukuri** [comment]
Thanks 

> I'll keep on adding new things to the udroid project ✨
