### ISSUE TITLE
Xrdp support 

### ISSUE THREAD

**Issue by omsenjalia** [RandomCoderOrg/ubuntu-on-android#111]
**Is your feature request related to a problem? Please describe.**
Yep! It's the graphics problem

**Describe the solution you'd like**
I would like a solution to add xrdp (remote desktop or Rdp) support, as it would increase graphics and the overall performance as it's just better

**Describe alternatives you've considered**
Adding a options in install script where you have to choose between rdp or vnc

**Additional context**
Thus would really really improve the speed.

**Comment by SaicharanKandukuri** [comment]
@omxpro 
here is documentation on setting up xrdp https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui#setting-up-xrdp, but It won't increase graphics performance.

The best solution is to try out `termux-x11`
> https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui/termux-x11

**Comment by omsenjalia** [comment]
Ty
