### ISSUE TITLE
Move back to Ubuntu 20.04

### ISSUE THREAD

**Issue by omsenjalia** [RandomCoderOrg/ubuntu-on-android#112]
Is there a way to move back to Ubuntu 20.04? I liked it's ii and stuff it was just faster for me, and I just liked it?

**Comment by SaicharanKandukuri** [comment]
@omxpro 
Udroid started shipping rootfs from Ubuntu version 21.04
Ubuntu 20.04 is not available

> You can install the oldest udroid version with these commands

```bash
# install dependencies
apt update; apt upgrade -y ; apt install -y pulseaudio proot-distro git -y
# clone the code
git clone -b v00-snapshot https://github.com/RandomCoderOrg/ubuntu-on-android
# run the installer
cd ubuntu-on-android
bash install.sh
# install
proot-distro install hippo
```

**Comment by omsenjalia** [comment]
Which Ubuntu version is it?

**Comment by SaicharanKandukuri** [comment]
ubuntu 21.04

**Comment by v8karlo** [comment]
Installed new 21.10
Panel freezes and is slower than 21.04.

Rolled back to 21.04 where everything is working just fine.

21.04 draw windows faster.

Tried to make x11 , but had issues and can not make it work.

**Comment by GitEin11** [comment]
after installing focal:xfce4, checking it. 21.04 is installed instead of 20.04
