### ISSUE TITLE
I cannot start udroid

### ISSUE THREAD

**Issue by Omar2547** [RandomCoderOrg/ubuntu-on-android#113]
It says :
/bin/su: error while loading shared libraries: libpam.so.0: cannot open shared object file: No such file or directory
?? program exited unexpectedly...

I think i should reinstall it but it takes a lot of data , so please help me if you have a solution ..

**Comment by SaicharanKandukuri** [comment]
`libpam` is available with package `libpam0g` 
try installing it with `apt install libpam0g -y`

**Comment by Omar2547** [comment]
It says :
Unable to locate package libpam0g

**Comment by SaicharanKandukuri** [comment]
@Omar2547 

can you post more info like

- screenshots 
- what `cmd` triggered that issue
- How to recreate that issue
