### ISSUE TITLE
Vscode not working

### ISSUE THREAD

**Issue by ghost** [RandomCoderOrg/ubuntu-on-android#115]
I can't run vscode, is there something I'm missing?

**Comment by SaicharanKandukuri** [comment]
if you logged in as root then use
```bash
mkdir .vscode-root
sudo code --user-data-dir="~/.vscode-root"
```

**Comment by ask9027** [comment]
> if you logged in as root then use
> 
> ```shell
> mkdir .vscode-root
> sudo code --user-data-dir="~/.vscode-root"
> ```

Not working

**Comment by SaicharanKandukuri** [comment]
try using in non-root user session

**Comment by kinoosaki** [comment]
try `code --no-sandbox` in terminal?
