### ISSUE TITLE
How to run an application on a nonroot user

### ISSUE THREAD

**Issue by Aridlvory** [RandomCoderOrg/ubuntu-on-android#118]
I don't know how to start an app on a nonroot user. I tried starting vnc on a nonroot user but it didn't work

**Comment by SaicharanKandukuri** [comment]
> I tried starting vnc on a nonroot user but it didn't work

can you describe what you did!

**Comment by Aridlvory** [comment]
Created a nonroot user
`useradd aridlvory`
And started vnc
`startvnc`
And then it asked password and then
![Screenshot_20220215-195359_Termux.jpg](https://user-images.githubusercontent.com/78092537/154081190-c6ce6ae6-63ad-4536-ac51-96ee9696f2f4.jpg)

**Comment by SaicharanKandukuri** [comment]
try this
from root

```bash
cp /root/.vnc/xstartup /home/aridlvory/.vnc/xstartup
chmod 007 /home/aridlvory/.vnc/xstartup
```

###### DOCS on creating non-root user: https://udroid-rc.gitbook.io/udroid-wiki/using-udroid/non-root-users

**Comment by Aridlvory** [comment]
Same error
![Screenshot_20220215-195958_Termux.jpg](https://user-images.githubusercontent.com/78092537/154082362-1d2eef19-b4a5-4e2b-ba41-c953221b4064.jpg)

**Comment by Aridlvory** [comment]
No...
File not found error changed to permission denied

**Comment by SaicharanKandukuri** [comment]
from aridlvory 
fix exec permissions
```
chmod +x ~/.vnc/xstartup
```

**Comment by Aridlvory** [comment]
Same error
PERMISSION DENIED

**Comment by ask9027** [comment]
I just found it ,
First remove all permissions of xstartup in user account, then give +xrw permission 
Now start vnc
