### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by thesuperfatcat** [RandomCoderOrg/ubuntu-on-android#119]
Hello, why i can't install udroid? I've seen this error before nethunter kali installation, and the installation failed. Am using android11 arm32 cpu

![termux_error](https://user-images.githubusercontent.com/56415358/154151033-02f13006-a8d8-444d-b64c-32834a9e47a6.png)

**Comment by SaicharanKandukuri** [comment]
can you provide mode info @thesuperfatcat 
like `termux-info` out

**Comment by thesuperfatcat** [comment]
> can you provide mode info @thesuperfatcat like `termux-info` out

![2648_Termux](https://user-images.githubusercontent.com/56415358/154648484-f4c70958-0c98-4779-a134-af8745c4f809.png)
I tried the same setups on different devices. Rootfs cannot extract archive packages, the same problem occurs in nethunter kali setups. I'm tried to extract the package with -tar commands, but it cannot extract.
