### ISSUE TITLE
Authorization failed in vnc server

### ISSUE THREAD

**Issue by ask9027** [RandomCoderOrg/ubuntu-on-android#122]
I logged in as user in udroid and view at vncserver but when i minimise vnc viewer for some time it's asking for password and i enter user password but it's showing Authorisation failed.
Please help me regarding this problem.
Thank
![Screenshot_2022-03-01-21-23-37-108_com realvnc viewer android](https://user-images.githubusercontent.com/61283438/156204011-f776b48c-39d2-46a2-8744-962fa80ba950.jpg)

**Comment by SaicharanKandukuri** [comment]
Try killing the session
```bash
vncserver --kill :*
```

And start it back again

**Comment by ask9027** [comment]
This is only way?

**Comment by SaicharanKandukuri** [comment]
Yep
Screen locks in proot won't work cause of android SELINUX

There is a workaround ( but it should be done before starting vnc )
