### ISSUE TITLE
Error "signal 9" after few seconds running

### ISSUE THREAD

**Issue by trash-anger** [RandomCoderOrg/ubuntu-on-android#123]
Hi,

Thank you for this beautiful work ! 
I just discovered this and after a fresh install I'm able to run on ubuntu for few seconds before receiving this message on termux:
`[Process completed (signal 9) - press Enter]`
I'm not sure but it seems it's on the termux parent session that it occurs as when I push Enter, termux closes...

I've been trying to find relevant logs but as the session is not gracefully closed, I found nothing.

Do you have any guess about how to debug it?

Oh! By the way... I'm running on Dex. I'm not sure if it can cause an issue but who knows... (not me at least)

**edit:** I just tried out of Dex and it's behaving the same... :/

**Comment by SaicharanKandukuri** [comment]
@trash-anger
It probably caused by phantom process killer in android v12
Checkout this discussion
- #117
