### ISSUE TITLE
Snap Doesn't Work

### ISSUE THREAD

**Issue by GUUser91** [RandomCoderOrg/ubuntu-on-android#127]
I tried to install Chromium with snap. But I get an error message

![snap](https://user-images.githubusercontent.com/77461922/157163815-1ca669c8-54a8-4efc-9baf-fb7710798a33.png)

I found a workaround solution in this page. But the third command doesn't work.
https://github.com/microsoft/WSL/issues/5126#issuecomment-653715201

The first command works
sudo apt-get update && sudo apt-get install -yqq daemonize dbus-user-session fontconfig

The second command works
sudo daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target

But the third command doesn't
exec sudo nsenter -t $(pidof systemd) -a su - $LOGNAME

I get an error message

![snap 2](https://user-images.githubusercontent.com/77461922/157164061-960f10ef-56e2-4640-aeda-2d0879302aa1.png)

**Comment by SaicharanKandukuri** [comment]
Systemd/init won't start in proot environment
Its never intended to work in it!
