### ISSUE TITLE
Termux X11 - fatal server error, can't connect to Wayland server

### ISSUE THREAD

**Issue by lmservas** [RandomCoderOrg/ubuntu-on-android#133]
Upon executing the following command per instructions in Termux

XDG_RUNTIME_DIR=$PREFIX/bin Xwayland -ac :1 > /dev/null &

It fails and outputs the following errors:

❯ XDG_RUNTIME_DIR=$PREFIX/bin Xwayland -ac :1 > /dev/null &
[1] 21875
could not connect to wayland server
(EE)
Fatal server error:
(EE) Couldn't add screen
(EE)
[1]  + 21875 exit 1     XDG_RUNTIME_DIR=$PREFIX/bin Xwayland -ac :1 > /dev/null

**Comment by SaicharanKandukuri** [comment]
which termux-x11 are you using?

**Comment by daemen85** [comment]
> which termux-x11 are you using?

I'm using udroid xfce4 I got the same issue

**Comment by ghost** [comment]
> > which termux-x11 are you using?
> 
> I'm using udroid xfce4 I got the same issue

he is talking about termux-x11 (like what version you are using and from where you downloaded, that termux x11 app). not the udroid xfce4

**Comment by Trass3r** [comment]
I tried the https://github.com/termux/termux-x11/releases APK and `pkg install xwayland termux-x11`.

```
$ export XDG_RUNTIME_DIR=${TMPDIR}
$ termux-x11 &
Starting: Intent { cmp=com.termux.x11/.MainActivity }
Failed starting Termux:X11: timeout
```

Even though the app does come up and prints "service created".

It complained about a missing `../usr/libexec/termux-x11/termux-startx11` in the beginning though.

Edit: ah ok the apk isn't compatible with the official package. Needed to install the corresponding .deb manually via `dpkg -i`.
