### ISSUE TITLE
Pre installed Android studio 

### ISSUE THREAD

**Issue by Bhuwneshwar** [RandomCoderOrg/ubuntu-on-android#136]
Try this Ubuntu on Android studio install but not successful so i 
Request to pre installed Android studio on this Ubuntu please 🥺🥺🥺

**Comment by SaicharanKandukuri** [comment]
We can add Android studio to udroid but android studio is not officially supported to `arm64` which causes failure in building applications

And proot `ptrace()` is so much unoptimized to a run-heavy app like Android Studio

**Comment by ask9027** [comment]
> Try this Ubuntu on Android studio install but not successful so i Request to pre installed Android studio on this Ubuntu please 🥺🥺🥺

Visit [this](https://github.com/ask9027/Install-Android-Studio-in-Termux/blob/main/README.md)  to use Android Studio.

**Comment by SaicharanKandukuri** [comment]
That's great @ask9027 
👏

**Comment by ask9027** [comment]
> > Try this Ubuntu on Android studio install but not successful so i Request to pre installed Android studio on this Ubuntu please pleading_facepleading_facepleading_face
> 
> Visit [this](https://github.com/ask9027/Install-Android-Studio-in-Termux/blob/main/README.md) to use Android Studio.

Updated...

**Comment by ghost** [comment]
android studio and it's dependencies are hella. and will increase the size twice. also android studio only works on arm64 (unofficially), and it's not fully stable, there could be many users getting errors with it if it get as pre installed. those who want to install it, they could just install it and run.
