### ISSUE TITLE
How to validate signed pdf

### ISSUE THREAD

**Issue by ask9027** [RandomCoderOrg/ubuntu-on-android#138]
guys , is there any way to validate digital signeture in udroid?
I want validate downloaded aadhaar pdf.
Please help me.

**Comment by SaicharanKandukuri** [comment]
`md5` or `sha256sum` works better

**Comment by ask9027** [comment]
> `md5` or `sha256sum` works better

Don't understand what you say...?

I need to validate digital signature not file md5 or sha256sum

**Comment by SaicharanKandukuri** [comment]
if its the case to verify digital signature of PDF's
I Suggest you following common tool like `pdfsig`

Its available in package in `poppler-utils`
```bash
apt install -y poppler-utils
```

**Comment by ask9027** [comment]
I used this libraby but it's showing wrong password in terminal.
I want to validate this aadhaar pdf..
![IMG_20220324_203432](https://user-images.githubusercontent.com/61283438/159946987-dd52b307-3b42-457f-98f9-d5d1c68912c2.jpg)

- 
![Screenshot_2022-03-24-20-39-50-926_com realvnc viewer android](https://user-images.githubusercontent.com/61283438/159947932-99a7d5d4-dea2-4e8e-8fba-086c2df67b29.jpg)

**Comment by SaicharanKandukuri** [comment]
probably bug in `pdfsig`
or incorrect usage
