### ISSUE TITLE
install.sh connection time out

### ISSUE THREAD

**Issue by Alextrapixel** [RandomCoderOrg/ubuntu-on-android#139]
Hi, 
when I run the installer, it got connection time out
`Could not connect to dl.kcubeterm.me:443 (99.83.154.118), connection timed out`
any issue in file server
![Screenshot_20220324-235215_Termux](https://user-images.githubusercontent.com/59244353/159970826-90e40d04-88c9-4efa-80aa-c5e7c9e0e2a2.jpg)

thanks before...

**Comment by SaicharanKandukuri** [comment]
That's from Termux App
Try using `termux-change-repo` to change termux package repo

If it doesn't work
I suggest you making issue at https://github.com/termux/termux-app/issues

**Comment by Alextrapixel** [comment]
It works... thanks @SaicharanKandukuri 🙂
