### ISSUE TITLE
unable to install udroid

### ISSUE THREAD

**Issue by ask9027** [RandomCoderOrg/ubuntu-on-android#141]
i just remove termux app, but when going install udroid using provided script grtting error `no DISTRO_NAME` found.
I think need to change in install.sh .
![Screenshot_2022-03-29-16-42-11-420_com termux](https://user-images.githubusercontent.com/61283438/160603499-2ca160a1-3a7f-4c4c-97b6-209f91b07e73.jpg)
![Screenshot_2022-03-29-17-20-18-288_com termux](https://user-images.githubusercontent.com/61283438/160604965-4d681f63-ffcf-47fb-9752-b136142debe1.jpg)
@SaicharanKandukuri

**Comment by SaicharanKandukuri** [comment]
Thanks for noticing us @ask9027 
This issue is been fixed in [ 0c36931618318302bb3bb04edb40ffc787232df2 ]

You can patch udroid with
```bash
rm -rf ~/../usr/bin/etc/proot-distro/focal-xfce4.sh
```

This solves all the problems and you can udroid
✌

**Comment by ask9027** [comment]
> Thanks for noticing us @ask9027 This issue is been fixed in [ [0c36931](https://github.com/RandomCoderOrg/ubuntu-on-android/commit/0c36931618318302bb3bb04edb40ffc787232df2) ]
> 
> You can patch udroid with
> 
> ```shell
> rm -rf ~/../usr/bin/etc/proot-distro/focal-xfce4.sh
> ```
> 
> This solves all the problems and you can udroid v

Thanks ... :+1:
