### ISSUE TITLE
Install Chromium

### ISSUE THREAD

**Issue by Alextrapixel** [RandomCoderOrg/ubuntu-on-android#142]
Hi again, any idea where I can install **chromium**? thanks...
btw nice work @SaicharanKandukuri and team, your work really help a lot for me when I was away from my PC. 
VSCode, Inkscape, even Blender 3D work good in udroid. Nice 👍

**Comment by ghost** [comment]
> Hi again, any idea where I can install **chromium**? thanks... btw nice work @SaicharanKandukuri and team, your work really help a lot for me when I was away from my PC. VSCode, Inkscape, even Blender 3D work good in udroid. Nice 👍

consider checking wiki before asking... also
https://github.com/RandomCoderOrg/ubuntu-on-android/wiki/chromium-in-udroid

**Comment by Alextrapixel** [comment]
ouch, missing that wiki. thanks for the note. sorry for my miss.
