### ISSUE TITLE
Question regarding using jammy tar all with udroid

### ISSUE THREAD

**Issue by lmservas** [RandomCoderOrg/ubuntu-on-android#145]
Instructions say to use the command:

udroid --suite jammy -i raw

Is this supposed to be after install.sh and in place of udroid -i xfce4?

Thx!!

**Comment by SaicharanKandukuri** [comment]
No `udroid --suite jammy -i raw` installs ubuntu 22.04 without any desktop environment

**Comment by v8karlo** [comment]
Can you make Udroid 22.04 release ?

Something like V4 Udroid ?

If I install 22.04 , is it possible to implement shared clipboard Android-Ubuntu with 22.04 if used with termux-x11 ?
Can 22.04 use Xfce4 as GUI ?
Will the termux-x11 work with 22.04 ?

Is 22.04 LTS ? If it is then is better to install 22.04 !

Can you share some light on the subject ?

**Comment by SaicharanKandukuri** [comment]
@v8karlo
Yep
you expected it correct  but it's not v4 but way soon
here are udroid plans after `April 12`
https://github.com/RandomCoderOrg/ubuntu-on-android/milestones

You know this already posted in discord
https://discord.com/channels/892727774828199976/892736496757514250/960798680405934120

**Comment by v8karlo** [comment]
Outstanding ! 

Didn't realised about the plans .
Can't wait to see it operating .
#

Thank you for your efforts and excellent job doing !

#
