### ISSUE TITLE
Why can't I edit files in the root folder?

### ISSUE THREAD

**Issue by Kyant0** [RandomCoderOrg/ubuntu-on-android#146]
![Screenshot_20220406-144618](https://user-images.githubusercontent.com/76829190/161912796-bad9f28f-9cbf-40fa-b024-2a719b9ada80.png)

I have logged in as root, but the files in the home folder don't allow me to modify.

**Comment by SaicharanKandukuri** [comment]
Try
```bash
sudo chown -Rv $USER:USER ~/Pictures
```
