### ISSUE TITLE
GL4ES Beta testing for termux 

### ISSUE THREAD

**Issue by SaicharanKandukuri** [RandomCoderOrg/ubuntu-on-android#15]
I am so happy to say **gl4es** is finally working in termux inside proot-environment 
- About [gl4es](https://github.com/ptitSeb/gl4es)
>GL4ES is a OpenGL 2.1/1.5 to GL ES 2.0/1.1 translation library, with support for Pandora, ODroid, OrangePI, CHIP, Raspberry PI, Android, Emscripten and AmigaOS4.

This features improves
![Screenshot_20210614-162434_VNC Viewer](https://user-images.githubusercontent.com/68287637/122002331-3bcac180-cdcf-11eb-9f34-1a747c34f1ab.jpg)

- `~60-120 fps` vnc performance
- Less screen tearing 
- everything is performance
- Chance to run even `Box86` and games in termux
> Recommended to use RealVNC app for the best experience

<hr>

 ## Installing this new feature
- install termux app from https://termux.com
As it set to beta code is stored in another `gl4es-patch`
- Here is the code to install
- just copy the below lines in termux :+1: 
```bash
# update your termux apt indexes
apt update; apt upgrade -y
# download the code
git clone -b gl4es-patch https://github.com/RandomCoderOrg/ubuntu-on-android.git
# install
cd ubuntu-on-android; bash install.sh
proot-distro install hippo

# Login 
proot-distro login hippo
```
After logging in it gl4es compiling so please be patient untill it completes 

## what you do
- Install this and share you screen shots to get featured in our docs and repo 
- Notice us if you have any problem or guide in doing things

- Join our community to make a chat
- - Discord https://discord.gg/y432PhPYCS

**Comment by abhikatta** [comment]
Yes!!!! 🔥🔥🔥

**Comment by Heasterian** [comment]
If you have Adreno GPU with KGSL support you don't need GL4ES, you can use Turnip driver with Zink to have hardware acceleration and support of OpenGL 3.0.

**Comment by Heasterian** [comment]
To compile it in proot, you need to add `#define __user` at the beginning of src/freedreno/vulkan/tu_kgsl.c

Also patch from the end of this issue increases compatibility https://gitlab.freedesktop.org/mesa/mesa/-/issues/4907

**Comment by ayon-ssp** [comment]
🔥🔥🔥🔥

**Comment by SaicharanKandukuri** [comment]
> To compile it in proot, you need to add `#define __user` at the beginning of src/freedreno/vulkan/tu_kgsl.c
> 
> Also patch from the end of this issue increases compatibility https://gitlab.freedesktop.org/mesa/mesa/-/issues/4907

Thanks for your suggestion @Heasterian We would like to hear more about that in discussion or here to make sure snapdragon user don't get confused 😊

**Comment by Heasterian** [comment]
If you have phone with Adreno GPU supporting KGSL, you can get GPU acceleration by compiling mesa with those two patches I mentioned. Stablest working version (with a bit more changes as It's older) you can find in git of Grima04 https://github.com/Grima04/mesa-turnip-kgsl Instalation guide is in README. You can find mainline Mesa patched in my git https://github.com/Heasterian/mesa/

You need to export or add to bash.rc GALLIUM_DRIVER=zink and if it will try to use lavapipe instead of Turnip, set VK_ICD_FILES to idc of freedreno/turnip (I think it's stored in /usr/local/share/vulkan/icd.d/ directory by default).

**Comment by SaicharanKandukuri** [comment]
Ya and also for fellow mali users
check this out https://docs.mesa3d.org/drivers/panfrost.html
https://www.youtube.com/watch?v=aJhV7K80OvQ&t=81s

- Youtube video on benchmarking Open-GL panforst with glmark2 on termux/proot ubuntu-on-android
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/aJhV7K80OvQ/0.jpg)](https://www.youtube.com/watch?v=aJhV7K80OvQ)

**Comment by Heasterian** [comment]
@SaicharanKandukuri It's benchmark of llvmpipe as you can see in terminal at this moment https://youtu.be/aJhV7K80OvQ?t=44

Afaik, you can't load hardware OpenGL driver, that's why I'm using one for Vulkan that can be loaded in userspace and Zink using it.

**Comment by SaicharanKandukuri** [comment]
Before I check zink out and dig into this zink driver
will this work in Mali too cause you mentioned only andreno in your comments

**Comment by Heasterian** [comment]
Zink is just using Vulkan driver to render OpenGL. Android allows to load Vulkan driver in userspace that's why it can work in proot/chroot. For Mali you probably need to wait for further developement of Vulkan driver.

**Comment by SaicharanKandukuri** [comment]
ya that's why I chose penforst and I don't know much about Zink. By the way can you can you join our discord and share you benchmark score!

**Comment by TOXIC-KID** [comment]
Will this work on opengl3.2

**Comment by SaicharanKandukuri** [comment]
Nope GL4ES is a open GL 2.1
>GL4ES is a OpenGL 2.1/1.5 to GL ES 2.0/1.1 translation library, with support for Pandora, ODroid, OrangePI, CHIP, Raspberry PI, Android, Emscripten and AmigaOS4

**Comment by TOXIC-KID** [comment]
> Nope GL4ES is a open GL 2.1
> 
> > GL4ES is a OpenGL 2.1/1.5 to GL ES 2.0/1.1 translation library, with support for Pandora, ODroid, OrangePI, CHIP, Raspberry PI, Android, Emscripten and AmigaOS4

Is there any way in which I could get some more FPS without rooting (I mean a faster chroot  
🙂) Am a noob so 🙂

**Comment by SaicharanKandukuri** [comment]
Create another issue for that!

**Comment by Randomae** [comment]
Found this and i think ill test it even if i have a Mali G71 it may work and ill share my experience when its installed and compiled

**Comment by Randomae** [comment]
Um it just dropped at ton of cannot open:function not implemented

**Comment by SaicharanKandukuri** [comment]
Can you share logs @Randomae

**Comment by TOXIC-KID** [comment]
> Um it just dropped at ton of cannot open:function not implemented

I got a bit of socket ignored error but its working but mine is opengl3.2 so can't test it

**Comment by Randomae** [comment]
Its too long but basically it didnt do anything it didint extract it because of that i think

**Comment by Randomae** [comment]
The termux scrollback cloudnt store most of it i think

**Comment by Randomae** [comment]
It may be a problem with tar

**Comment by TOXIC-KID** [comment]
> The termux scrollback cloudnt store most of it i think

I think if I minize the u could get more

**Comment by Randomae** [comment]
i have it like that most of the time and even like that it didnt work

**Comment by Randomae** [comment]
Ill try installing it again

**Comment by SaicharanKandukuri** [comment]
> Um it just dropped at ton of cannot open:function not implemented

send a screenshot

**Comment by Randomae** [comment]
its working now and installing build dependencies

**Comment by Randomae** [comment]
Just had to reinstall it

**Comment by Randomae** [comment]
Now ill just wait

**Comment by Randomae** [comment]
I cant upload directly the screenshot and i had to use a link https://ibb.co/604C15q

**Comment by Randomae** [comment]
A bit slow but ill check more i just installed it

**Comment by SaicharanKandukuri** [comment]
also, Join our discord community to stay tuned for the next beta tests and upgrades
https://discord.gg/y432PhPYCS
[![Support Server](https://img.shields.io/discord/851345998831157288.svg?label=Discord&logo=Discord&colorB=7289da&style=for-the-badge)](https://discord.gg/y432PhPYCS)

**Comment by Randomae** [comment]
Oks and firefox goes slow at start but then it goes better than on normal and when moving windows a bit slow too

**Comment by Randomae** [comment]
The phone is so cold
