### ISSUE TITLE
Run on VPS

### ISSUE THREAD

**Issue by omsenjalia** [RandomCoderOrg/ubuntu-on-android#154]
Is there a way to run this on a VPS? VPS means a machine without a GUI and i want a GUI

**Comment by omsenjalia** [comment]
..

**Comment by SaicharanKandukuri** [comment]
I forgot to look here!
Yes you can chroot udroid filesystem in a vps linux host and start a display

**Comment by omsenjalia** [comment]
> I forgot to look here! Yes you can chroot udroid filesystem in a vps linux host and start a display

Any guides?
