### ISSUE TITLE
Any idea how to port USB

### ISSUE THREAD

**Issue by xdevkroom** [RandomCoderOrg/ubuntu-on-android#160]
For example i installed arduino to flash AVR but i cant reach USB 
any idea ??!!!

**Comment by SaicharanKandukuri** [comment]
this topic is under research
for now, there is just hope that it could work with android API

**Comment by SaicharanKandukuri** [comment]
This feature requires implements from termux-app

> try making an issue here: https://github.com/termux/termux-x11

✌️
