### ISSUE TITLE
Get back in root

### ISSUE THREAD

**Issue by MHR-S** [RandomCoderOrg/ubuntu-on-android#163]
After creating a user... can't get back to root...what is the password for su root????.

**Comment by MHR-S** [comment]
Is it possible to use Adobe software in it?? tried playonlinux but it can't be open with root

**Comment by SaicharanKandukuri** [comment]
use `exit` ot `ctrl+d` to get back to root
by default there is no root password

**Comment by MHR-S** [comment]
Thank you....Can i run adobe software in it?I need to run some adobe software,,,though there are some alternatives but they are not as good as adobes..So if it can be done...PLEASE ans how

**Comment by MHR-S** [comment]
Thanks for your reply...
Can i run adobe software in it?
