### ISSUE TITLE
Can t login

### ISSUE THREAD

**Issue by Cl1nkkk** [RandomCoderOrg/ubuntu-on-android#165]
~ $ proot-distro install udroid-focal-xfce4

Error: distribution 'udroid-focal-xfce4' is already installed.

Log in:     proot-distro login udroid-focal-xfce4
Reinstall:  proot-distro reset udroid-focal-xfce4
Uninstall:  proot-distro remove udroid-focal-xfce4

~ $ proot-distro login udroid-focal-xfce4
su: cannot open session: Error in service module                                        ~ $

**Comment by AnninoDr4** [comment]
> this is probably device specific issue

try this command to patch proot-distro to use bash instead of `su`. then try to login again with `udroid -l xfce4`
```bash
sed -i '1066s/\/bin\/su/\/bin\/bash/' ~/../usr/bin/proot-distro
```

**Comment by Cl1nkkk** [comment]
Not working
