### ISSUE TITLE
Xfce4-panel freezes, unresponsive 

### ISSUE THREAD

**Issue by sdanfa** [RandomCoderOrg/ubuntu-on-android#168]
Hi,
I installed everything via your script and updated the os via apt but the Xfce4-panel on top freezes then I can't click in the items with my touchscreen/mouse. Any way to fix it?

Thanks.

**Comment by SaicharanKandukuri** [comment]
can you share the log file
like `./vnc/*.log`
or try
```bash
xfce4-panel -r
```

**Comment by sdanfa** [comment]
> can you share the log file
> like `./vnc/*.log`
> or try
> ```bash
> xfce4-panel -r
> ```

Nvm, I deleted Xfce4-panel config XML file and now it doesn't freeze. Thanks for your help.
