### ISSUE TITLE
Right click

### ISSUE THREAD

**Issue by sdanfa** [RandomCoderOrg/ubuntu-on-android#169]
Hi,
How can I right click with Direct Mode? I tried also emulate mouse, I can right click with it but the mouse goes to a random direction when I use double touch on touchpad.

Thanks.

**Comment by SaicharanKandukuri** [comment]
@sdanfa what app you're using

**Comment by sdanfa** [comment]
> @sdanfa what app you're using 

I'm using the Termux:X11, Termux:GUI app companion. The app that works almost like vnc client. Thanks.

**Comment by SaicharanKandukuri** [comment]
use emulated touchpad and tap with two fingers
