### ISSUE TITLE
Error on starting vnc server

### ISSUE THREAD

**Issue by mizzunet** [RandomCoderOrg/ubuntu-on-android#17]
```
root@localhost:~# vncserver :1
/usr/bin/xauth:  timeout in locking authority file /root/.Xauthority
/usr/bin/xauth:  timeout in locking authority file /root/.Xauthority
vncserver: Can't create pid file '/root/.vnc/localhost.localdomain:5901.pid': Required key not available
```

**Comment by mizzunet** [comment]
Then I deleted .vnc and tried again, however now this error
```
root@localhost:~/.vnc# vncserver :1

You will require a password to access your desktops.

Password:
Verify:
Would you like to enter a view-only password (y/n)?
Couldn't open /root/.vnc/passwd for writing
```

**Comment by SaicharanKandukuri** [comment]
May be the .vnc folder contens are missing or corrupted
Try do this
1. Remove .vnc folder `rm -rf ~/.vnc`
2. purge tigervnc `apt install --reinstall tigervnc-standalone-server -y`
3. Remove Unix locks `rm -rf /tmp/X11-unix/*`
### Reconfigure vnc
1. Set password `vncpasswd`
2. Start VNC `vncserver :1`

**Comment by SaicharanKandukuri** [comment]
To prevent future errors be sure you kill the server before leaving it
`vncserver --kill :1`

**Comment by mizzunet** [comment]
> May be the .vnc folder contens are missing or corrupted
> Try do this
> 
> 1. Remove .vnc folder `rm -rf ~/.vnc`
> 2. purge tigervnc `apt install --reinstall tigervnc-standalone-server -y`
> 3. Remove Unix locks `rm -rf /tmp/X11-unix/*`
> 
> ### Reconfigure vnc
> 1. Set password `vncpasswd`
> 2. Start VNC `vncserver :1`

Having this error on 2,
```
root@localhost:~# apt install --reinstall tigervnc-standalone-server -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 952 kB of archives.
After this operation, 0 B of additional disk space will be used.
Err:1 http://ports.ubuntu.com/ubuntu-ports hirsute/universe arm64 tigervnc-standalone-server arm64 1.11.0+dfsg-2
  Could not open file /var/cache/apt/archives/partial/tigervnc-standalone-server_1.11.0+dfsg-2_arm64.deb - open (126: Required key not available) Unable to determine file size for fd -1 - fstat (9: Bad file descriptor) Could not open file /var/cache/apt/archives/partial/tigervnc-standalone-server_1.11.0+dfsg-2_arm64.deb - open (126: Required key not available) [IP: 91.189.91.39 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/universe/t/tigervnc/tigervnc-standalone-server_1.11.0+dfsg-2_arm64.deb  Could not open file /var/cache/apt/archives/partial/tigervnc-standalone-server_1.11.0+dfsg-2_arm64.deb - open (126: Required key not available) Unable to determine file size for fd -1 - fstat (9: Bad file descriptor) Could not open file /var/cache/apt/archives/partial/tigervnc-standalone-server_1.11.0+dfsg-2_arm64.deb - open (126: Required key not available) [IP: 91.189.91.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

`apt-get update  --fix-missing` does nothing but more errors

**Comment by SaicharanKandukuri** [comment]
Do `apt install -f`

**Comment by mizzunet** [comment]
```
root@localhost:~# apt install -f
Reading package lists... Error!
E: Unable to mkstemp /tmp/clearsigned.message.enGicc - GetTempFile (126: Required key not available)
E: The package lists or status file could not be parsed or opened.
```

**Comment by mizzunet** [comment]
My phone is OnePlus 5 and android version 11

**Comment by mizzunet** [comment]
I reinstalled by `proot-distro reset hippo`, and found this error 
```
[*] Registering Android-specific UIDs and GIDs...
id: ‘20331’: no such user: No such file or directory
id: ‘20331’: no such user: No such file or directory
id: ‘50331’: no such user: No such file or directory
id: ‘50331’: no such user: No such file or directory
[*] Running distro-specific configuration steps...
[*] Installation finished.
```

Also, I ran `apt update ` at first, it returned errors. Something went wrong at my end, I guess

**Comment by mizzunet** [comment]
I reinstalled by proot-distro reset hippo, and found this error 
```
[*] Registering Android-specific UIDs and GIDs...
id: ‘20331’: no such user: No such file or directory
id: ‘20331’: no such user: No such file or directory
id: ‘50331’: no such user: No such file or directory
id: ‘50331’: no such user: No such file or directory
[*] Running distro-specific configuration steps...
[*] Installation finished.
```

Also, I ran `apt update ` at first, it returned errors. Something went wrong at my end, I guess

**Comment by SaicharanKandukuri** [comment]
The logs you shown they happen in all devices.

**Comment by mizzunet** [comment]
Oh

**Comment by SaicharanKandukuri** [comment]
Ya they happen proot-distro sets up groups

**Comment by mizzunet** [comment]
The error `126: Required key not available` seems like mount issue

**Comment by mizzunet** [comment]
I tried `chown root:root /*`
This happens
 ```
chown: changing ownership of '/system': Read-only file system
chown: changing ownership of '/vendor': Read-only file system

```

**Comment by SaicharanKandukuri** [comment]
Ya you can't change permissions for /system and /vendor, cause it is working in proot and android won't allow to do it

This also happens in all devices when you do `chown root:root /*` and 

> chown: changing ownership of '/system': Read-only file system
> chown: changing ownership of '/vendor': Read-only file system

**Comment by mizzunet** [comment]
Uh. Is there any kind of logs that I can share?

**Comment by SaicharanKandukuri** [comment]
is the problem persisting after reset?

**Comment by SaicharanKandukuri** [comment]
> Uh. Is there any kind of logs that I can share?

stdout (Output lines) after commands are all we have for this issue

**Comment by mizzunet** [comment]
> is the problem persisting after reset?

Yes it did persist. Now I'm reinstalling (cleared termux data and try again)

**Comment by SaicharanKandukuri** [comment]
Based on information you gave

maybe it because of old indexes

Try 
`apt clean; apt update`

**Comment by SaicharanKandukuri** [comment]
And try this
```bash
rm -rvf /var/lib/apt/lists/* 
apt clean
apt upgrade
```

**Comment by mizzunet** [comment]
Still happens even this reinstallation. Tried both `apt clean; apt update` and the other command, doesn't work.

**Comment by mizzunet** [comment]
This error keep showing
```
E: Could not open lock file /var/lib/apt/lists/lock - open (126: Required key not available)
E: Unable to lock directory /var/lib/apt/lists/
Reading package lists... Error!
E: Could not create temporary file for /var/cache/apt/srcpkgcache.bin - mkstemp (126: Required key not available)
E: The package lists or status file could not be parsed or opened.
```

**Comment by SaicharanKandukuri** [comment]
> And try this
> 
> ```shell
> rm -rvf /var/lib/apt/lists/* 
> apt clean
> apt upgrade
> ```

what about this

**Comment by mizzunet** [comment]
> what about this

This 
https://github.com/RandomCoderOrg/ubuntu-on-android/issues/17#issuecomment-864562818

**Comment by mizzunet** [comment]
I'm the only one having these errors right?

**Comment by SaicharanKandukuri** [comment]
well this is the first issue about something not working so i can't say and I never got during in my tests so something happened ​while installation 

share more like
- Termux version you are in

**Comment by mizzunet** [comment]
Termux Version 0.114 downloaded from FDroid
Android version 11 custom ROM
OnePlus 5
CPU: SDM835
RAM: 6GB

**Comment by SaicharanKandukuri** [comment]
> Android version 11 custom ROM

Strange!
Try to reinstall apt
```
apt install --reinstall apt
```

**Comment by mizzunet** [comment]
> > Android version 11 custom ROM
> 
> Strange!
> Try to reinstall apt
> 
> ```
> apt install --reinstall apt
> ```

That too has the same error ;(

**Comment by SaicharanKandukuri** [comment]
if it still like this
```
E: Could not open lock file /var/lib/apt/lists/lock - open (126: Required key not available)
E: Unable to lock directory /var/lib/apt/lists/
Reading package lists... Error!
E: Could not create temporary file for /var/cache/apt/srcpkgcache.bin - mkstemp (126: Required key not available)
E: The package lists or status file could not be parsed or opened.
```
Before doing this.
mkstemp is the thing that makes a temporary file securely
Based on my troubleshoot this error appeared once cause of a kernel issue with the same exit codes.
but I think that's not the reason for you

<hr>

Here is work through 

-  1. Kill apt existing processes ->   ``` pkill apt ; pkill dpkg ```
-  2. Try to delete locks and lists cache from apt 
```bash
rm -rvf /var/lib/apt/list
rm -rvf /var/lib/apt/lists/
rm -rvf /var/lib/dpkg/lock
```

Then try apt again

**Comment by mizzunet** [comment]
Executed those, then ran apt update, still the error happens

**Comment by SaicharanKandukuri** [comment]
same  error output again

**Comment by mizzunet** [comment]
Yes, this output https://github.com/RandomCoderOrg/ubuntu-on-android/issues/17#issuecomment-864562818

**Comment by ghost** [comment]
> ```
> root@localhost:~# apt install -f
> Reading package lists... Error!
> E: Unable to mkstemp /tmp/clearsigned.message.enGicc - GetTempFile (126: Required key not available)
> E: The package lists or status file could not be parsed or opened.
> ```
"Required key not available" means that `cifs.upcall` run by the kernel in response to the mount request was not able to get a Kerberos ticket for the CIFS server and from that generate the key needed for authenticating to the server (it would go in the kernel keyring of the client thread). This may cause because of android 11 custom rom which seems incompatible with termux/proot.

**Comment by SaicharanKandukuri** [comment]
I think the issue as I mentioned [here](https://github.com/RandomCoderOrg/ubuntu-on-android/issues/17#issuecomment-864571987)
> Based on my troubleshoot this error appeared once cause of a kernel issue with the same exit codes. 

and as  @GxmerSam  said in detailed
This issue caused by the custom ROM you are in. Official ROMs nowadays never get this cause this part is considered important and well maintained out of the box.

Try it in any official ROM or contact your custom ROM dev to fix this

for this state, it won't be fixed.

**Comment by mizzunet** [comment]
Maybe you're right, it's due to this ROM. I tried installing ubuntu-20.04 using proot and the error happens there too. Let me see in another ROM.
 I appreciate your help and your work. 🤗

Btw, I happened to know that (https://www.reddit.com/r/termux/comments/o4br6w/how_different_are_running_linux_by_chroot_proot/), chroot and native termux desktop have maximum performance than proot. While chroot may break host OS if anything wrong done, while native-way is a safe one. 
Would you consider making it for native running?  Wouldn't that make this more snappier?

**Comment by SaicharanKandukuri** [comment]
yes The native way work faster but Termux won't support all packages that required to make things that happened in hippo
and native termux can't do the syscalls or simulate systems' layout of UID's and GID's while  proot can as xeffer said
>It uses Linux debugging interface (ptrace) to control the process execution and hijack arguments and return values of system calls, so it can simulate a different file system layout and user/group ids

it can do syscalls(not all) to make most of the packages run! 
- if you want a lot of Linux and its packages running by compromising with android security patches then proot is the choice
- if performance is the point and with real basic Linux packages then native termux is the choice with x11-repo

**Comment by mizzunet** [comment]
How about chroot?
Btw I changed ROM guess what? I got this working :D

**Comment by SaicharanKandukuri** [comment]
Working on chroot in a private space by borrowing some techniques from pre existing projects

**Comment by mizzunet** [comment]
Very nice thank you

**Comment by SaicharanKandukuri** [comment]
#23
