### ISSUE TITLE
xfce4 cannot connect and Termux X11 shows black screen

### ISSUE THREAD

**Issue by GUUser91** [RandomCoderOrg/ubuntu-on-android#171]
I'm using termux x11 dev build version 1.02.06 and I installed the deb package.
https://github.com/termux/termux-x11/actions/runs/2418991974

I login using this command
`proot-distro login udroid-focal-xfce4 --shared-tmp`
And I export the display
`export DISPLAY=:0`
And I start xfce4
`dbus-launch --exit-with-session startxfce4`
And then I get an error message
`/usr/bin/startxfce4: X server already running on display :0
xrdb: Connection refused
xrdb: Can't open display ':0'
Unable to init server: Could not connect: Connection refused
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.`

I also tried this command
`DISPLAY=:1 xfce4-session`
And I get this error message
`Unable to init server: Could not connect: Connection refused
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.`

**Comment by SaicharanKandukuri** [comment]
Traditional methods to start display won't work without apps like termux-x11 or Realvnc
Checkout this documentation
  https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui
&
 https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui/termux-x11

**Comment by GUUser91** [comment]
@SaicharanKandukuri
Did you read the first sentence of my opening post? I said I am using the termux-x11 app, it is dev build version 1.02.06 and I installed the apk and the deb package. And I already followed the guide on the second documentation, I get the error message still.
Edit: I'm going to close this issue for now and I'm going to uninstall the regular termux and termux-x11 apps and install the dev builds instead and see where this goes.

Another edit: I want to point out that the udroid link below isn't thorough enough with the direction. It doesn't mention that you also have to install the Termux X11 deb package inside termux.
And that after you type this. 
`echo 'allow-external-apps = true' >> ~/.termux/termux.properties`
You have to restart the termux app for the changes to take effect.
https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui/termux-x11

**Comment by SaicharanKandukuri** [comment]
@GUUser91 
Yep I read that line!
That error occurs only when
 server isn't started correctly from termux side, `--shared-tmp` not used, missing external apps permission

In your case it's either 1 or 3rd

**Comment by SaicharanKandukuri** [comment]
> @SaicharanKandukuri Did you read the first sentence of my opening post? I said I am using the termux-x11 app, it is dev build version 1.02.06 and I installed the apk and the deb package. And I already followed the guide on the second documentation, I get the error message still. Edit: I'm going to close this issue for now and I'm going to uninstall the regular termux and termux-x11 apps and install the dev builds instead and see where this goes.
> 
> Another edit: I want to point out that the udroid link below isn't thorough enough with the direction. It doesn't mention that you also have to install the Termux X11 deb package inside termux. And that after you type this. `echo 'allow-external-apps = true' >> ~/.termux/termux.properties` You have to restart the termux app for the changes to take effect. https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui/termux-x11

It will be updated soon

**Comment by v8karlo** [comment]
Sometimes X-11 wont start at first try. I dont know why, but it happens.
Here in this discussion is the procedure which started X-11 for me.

https://github.com/RandomCoderOrg/ubuntu-on-android/discussions/152

Try to follow procedure just swap Jammy with udroid-focal-xfce4 if you wanna install focal.

And still can happen that it wont start at first try.
I HAD SOMETIMES EVEN 5 FAILS IN A ROLE UNTIL I SUCCEDDED !
Just try to start it again until it does!

The following part is for starting X-11 after installing everything.

#

The following part is the part you have to repeat if start fails !

#

`termux-x11 > /dev/null &`

`pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1`

`proot-distro login udroid-jammy-raw --shared-tmp -- runuser -l v8 -c 'DISPLAY=:0 xfce4-session'`

#

I hope you will make it start . !

#

**Comment by v8karlo** [comment]
Could be related to this issue  Build 174

https://github.com/termux/termux-x11/issues/129#issuecomment-1152990454

**Comment by SaicharanKandukuri** [comment]
> @SaicharanKandukuri Did you read the first sentence of my opening post? I said I am using the termux-x11 app, it is dev build version 1.02.06 and I installed the apk and the deb package. And I already followed the guide on the second documentation, I get the error message still. Edit: I'm going to close this issue for now and I'm going to uninstall the regular termux and termux-x11 apps and install the dev builds instead and see where this goes.
> 
> Another edit: I want to point out that the udroid link below isn't thorough enough with the direction. It doesn't mention that you also have to install the Termux X11 deb package inside termux. And that after you type this. `echo 'allow-external-apps = true' >> ~/.termux/termux.properties` You have to restart the termux app for the changes to take effect. https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui/termux-x11


This should work!
but if the problem won't solve then you can try this old fork 
- https://github.com/SaicharanKandukuri/T-X11/actions
