### ISSUE TITLE
Uninstall 21.04

### ISSUE THREAD

**Issue by agentzhao** [RandomCoderOrg/ubuntu-on-android#172]
Hi!

Followed the steps in the Readme and everything works successfully, however I wanted to install 20.04 focal instead. May I know the steps to do a clean uninstallation?

Cheers :)

**Comment by SaicharanKandukuri** [comment]
Just use
```bash
udroid -r xfce4
```
> You can use `proot-distro clear-cache` to remove extra cache

✌️

**Comment by agentzhao** [comment]
> Just use
> ```bash
> udroid -r xfce4
> ```
> > You can use `proot-distro clear-cache` to remove extra cache
> 
> ✌️

Thanks!
