### ISSUE TITLE
apt update error

### ISSUE THREAD

**Issue by sbgalex** [RandomCoderOrg/ubuntu-on-android#177]
sudo apt update
Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Ign:2 http://ports.ubuntu.com/ubuntu-ports hirsute InRelease
Ign:3 http://ports.ubuntu.com/ubuntu-ports hirsute-updates InRelease
Ign:4 http://ports.ubuntu.com/ubuntu-ports hirsute-backports InRelease
Ign:5 http://ports.ubuntu.com/ubuntu-ports hirsute-security InRelease
Err:6 http://ports.ubuntu.com/ubuntu-ports hirsute Release
  404  Not Found [IP: 185.125.190.36 80]
Err:7 http://ports.ubuntu.com/ubuntu-ports hirsute-updates Release
  404  Not Found [IP: 185.125.190.36 80]
Err:8 http://ports.ubuntu.com/ubuntu-ports hirsute-backports Release
  404  Not Found [IP: 185.125.190.36 80]
Err:9 http://ports.ubuntu.com/ubuntu-ports hirsute-security Release
  404  Not Found [IP: 185.125.190.36 80]
Reading package lists... Done
E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute-updates Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute-backports Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute-security Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by shubham-indalkar** [comment]
> sudo apt update Hit:1 http://packages.microsoft.com/repos/code stable InRelease Ign:2 http://ports.ubuntu.com/ubuntu-ports hirsute InRelease Ign:3 http://ports.ubuntu.com/ubuntu-ports hirsute-updates InRelease Ign:4 http://ports.ubuntu.com/ubuntu-ports hirsute-backports InRelease Ign:5 http://ports.ubuntu.com/ubuntu-ports hirsute-security InRelease Err:6 http://ports.ubuntu.com/ubuntu-ports hirsute Release 404 Not Found [IP: 185.125.190.36 80] Err:7 http://ports.ubuntu.com/ubuntu-ports hirsute-updates Release 404 Not Found [IP: 185.125.190.36 80] Err:8 http://ports.ubuntu.com/ubuntu-ports hirsute-backports Release 404 Not Found [IP: 185.125.190.36 80] Err:9 http://ports.ubuntu.com/ubuntu-ports hirsute-security Release 404 Not Found [IP: 185.125.190.36 80] Reading package lists... Done E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute Release' no longer has a Release file. N: Updating from such a repository can't be done securely, and is therefore disabled by default. N: See apt-secure(8) manpage for repository creation and user configuration details. E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute-updates Release' no longer has a Release file. N: Updating from such a repository can't be done securely, and is therefore disabled by default. N: See apt-secure(8) manpage for repository creation and user configuration details. E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute-backports Release' no longer has a Release file. N: Updating from such a repository can't be done securely, and is therefore disabled by default. N: See apt-secure(8) manpage for repository creation and user configuration details. E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute-security Release' no longer has a Release file. N: Updating from such a repository can't be done securely, and is therefore disabled by default. N: See apt-secure(8) manpage for repository creation and user configuration details.

I'm getting same error. Thought something is wrong with termux so reinstalled Ubuntu. I think it's end of support for Ubuntu 21.04.

![IMG_20220723_190227_1](https://user-images.githubusercontent.com/21367218/180607252-9514a4ec-a02d-4217-bc9a-5f90a04620b4.jpg)
