### ISSUE TITLE
Support for opengl 3.2

### ISSUE THREAD

**Issue by TOXIC-KID** [RandomCoderOrg/ubuntu-on-android#18]
How can I run this in opengl 3.2
I just wanted to get a bit more FPS🙂

**Comment by SaicharanKandukuri** [comment]
It not really possible to run OpenGL 3.1 or any other with full GPU power. But still, there is a way to improve things
Try This out:
- use vnc server  `apt install tigervnc-standalone-server ` and include xorg extensions packages `apt install tigervnc-xorg-extension`  
- For best performance use Bvnc or Nethunter vnc or you can opt RealVNC too
> I use [NethunterVNC](https://store.nethunter.com/en/packages/com.offsec.nhvnc/) most 

If you want more performance then use [Xserver-xsdl](https://play.google.com/store/apps/details?id=x.org.server) app 
###### Here is a tutorial to use Xserver Xsdl

1. Open Xserver-xsdl app wait until it shows a blue screen
2. Start your proot environment in termux then export DISPLAY environment variable `export DISPLAY=127.0.0.1:0`
3. The start your Desktop environment `startxfce4` (you may see logs ). The get back to Xserver-xsdl app you will see xfce4 running
