### ISSUE TITLE
Is it good

### ISSUE THREAD

**Issue by Greenarrow4245** [RandomCoderOrg/ubuntu-on-android#185]

**Comment by AnninoDr4** [comment]
its proot so depends on mobile

**Comment by Greenarrow4245** [comment]
Redmi note 10 pro will it work

**Comment by inari-codes** [comment]
pretty good specs i guess but it's running without gpu acceleration due to termux and proot limitations so it will run noticeably slower than android

**Comment by v8karlo** [comment]
As far as it is related to graphics, but computation side is same speed as Android .
So, one excel spreadsheet will be running at same speed as Android .
Photoshop will be running same speed as Android , lots of computation .

Movies , games and 3d animation software are bottleneck ,

For someone like me, who is using office  and web browsing is almost same as Android .
And I am gaming on Android DEX , so I have everything combining DEX and proot .

And that combinatoion is working damn good !

Yes , it is worth !

**Comment by inari-codes** [comment]
actually not though, file read/write will a bit slower and there's no way to run photoshop on linux without crazy hoops especially if you're on an android phone running a faked environment

**Comment by v8karlo** [comment]
Yea , true , true , indeed .

It is still on top of Termux , but usable , can say , for smaller tasks .

We will have to wait for Android 13 VM and see will be Google allowing us to play with containers .?
Preliminary peeks are promising .

But , never trust Google , will see .

**Comment by inari-codes** [comment]
I don't think Google will do that since Android is just a mobile OS made for most people to use, not actually made for tinkerers and coder and if you have enough money, just get a decent laptop/PC and dualboot Linux on it instead, **most** mobile hardware is still pretty limited

**Comment by v8karlo** [comment]
I do have , not decent , but very expensive gaming machine ,

and I am squezing every bit of power from it for fun .

Water Cooler is big enough to mount in a car , almost .

It is not that . This phone thing fascinated me and got me ,

probably only for some time .

But it got me for now . 

I do gaming Eve Online on 32" in 4K and it looks , fantastic !!!

**Comment by v8karlo** [comment]
But then, if A13 VM will not happen, why Microsoft bored to compile 
windows Arm64 ?

For what ?
