### ISSUE TITLE
xrdp

### ISSUE THREAD

**Issue by WindowHZT** [RandomCoderOrg/ubuntu-on-android#187]
I'm in your Ubuntu using a command
apt install xrdp

But this XRDP feature, it doesn't seem to work, when I use RD Client to connect to VNC, it is grey screen. RD Client Download link:
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients

**Comment by SaicharanKandukuri** [comment]
try this
https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui#setting-up-xrdp
