### ISSUE TITLE
Transmit files between Android and udroid? 

### ISSUE THREAD

**Issue by ghost** [RandomCoderOrg/ubuntu-on-android#189]
Hello, I wonder if it's possible to for udroid transmit files directly with the local Android system?

**Comment by SaicharanKandukuri** [comment]
**Transmit files!**
can you explain it @sunflowerrrleaf

**Comment by Hamzah234** [comment]
Go to computer tab in file manager on the distro, go to the folder thing inside it, open sdcard folder inside
