### ISSUE TITLE
Can it run in chroot ? And how do i install ubuntu on android

### ISSUE THREAD

**Issue by xDoge26** [RandomCoderOrg/ubuntu-on-android#196]

**Comment by v8karlo** [comment]
#

INSTALL LINUX ON TOP OF ANDROID WITHOUT ROOT .

#

There is an easy way and hard way .

Easy way https://github.com/RandomCoderOrg/ubuntu-on-android in a few steps .

And hard way https://github.com/RandomCoderOrg/ubuntu-on-android/discussions/152 IF YOU WANNA LEARN HOW TO DO IT .

Android does not allow any operational system different than Android to be installed on top of Android .

Thanks to the few man crew on Termux coders , they managed to hack proot option and bring Linux into Android .

So every Linux on Andoid is actually hack , and it works for now , pretty good .

#

**Comment by SaicharanKandukuri** [comment]
Ubuntu-on-android dosent have support for root/chroot
> But yes with some manuall scripts and lot of hacks you can chroot to the tarballs. ( But it's offtopic for this project)
