### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by XGilmar** [RandomCoderOrg/ubuntu-on-android#198]
Hey guys I am following the steps to install termux-11x but I always get this error please help me.

![IMG_20220918_175402](https://user-images.githubusercontent.com/86094668/190932009-f2faa294-ad22-4a79-a188-d773de2f7c0a.jpg)

> **Error**

![IMG_20220918_175537](https://user-images.githubusercontent.com/86094668/190932032-abd3bf40-6e7b-4c12-8a0d-2741952ef862.jpg)

**Comment by dontknowhy** [comment]
You should download the **termux-x11** package from github.

**Comment by SaicharanKandukuri** [comment]
@XGilmar 
try this in termux environment
```bash
pkg install x11-repo
apt update
pkg install xwayland

wget https://cdn.discordapp.com/attachments/892727774828199981/961100799407165510/termux-x11.deb
dpkg -i termux-x11.deb
```
