### ISSUE TITLE
Use alias

### ISSUE THREAD

**Issue by mizzunet** [RandomCoderOrg/ubuntu-on-android#20]
**Is your feature request related to a problem? Please describe.**
Typing the command `proot-distro login hippo` and `vncserver`
are nahhing
**Describe the solution you'd like**
Use alias commands

**Describe alternatives you've considered**
Made alias

**Comment by SaicharanKandukuri** [comment]
we are working on it 
Here are some shortcuts which are work in progress
Right before starting proot
- [X] `hippo` to login
- [X] `hippo startvnc` to startvnc from termux
- [X] `hippo stopvnc` to stopvnc from termux
- [ ] `hippo upgrade`
- [ ] `hippo purge`
- [ ] `hippo reset` 
& etc are coming soon.... 
To try out get in here https://github.com/RandomCoderOrg/fs-manager-hippo

and leave me a suggestion here👍

**Comment by mizzunet** [comment]
Good luck 🤗
