### ISSUE TITLE
Uninstall Softwares

### ISSUE THREAD

**Issue by nasyx-rakeeb** [RandomCoderOrg/ubuntu-on-android#203]
I noticed there are many unwanted softwares installed by default and i don't want them, for example i don't want sublime text editor, But when i remove it with `sudo apt --purge remove package-name` it doesn't delete it properly, it only releases some kb of storage however it should release approximately 120+ mb of storage which it has used. I want to know if there's a proper way to bulk delete installed software

**Comment by SaicharanKandukuri** [comment]
That problem is just with Sublime text cause they it works

Sublime text editor is installed under `/opt` or `/var`
