### ISSUE TITLE
Keyboard problem

### ISSUE THREAD

**Issue by BlackLordDSNR** [RandomCoderOrg/ubuntu-on-android#206]
Hello. I have a problem with the keyboard. When I try to switch to any language other than English, about half of the keyboard stops working. For example, when you press the keys J, K, L, Z, X, C, V, B, N, M, <, >, :, ", which in other layouts correspond to certain letters, nothing happens. How can this to correct?

**Comment by SaicharanKandukuri** [comment]
language support depends on the app you're using to view and control the desktop environment.

> udroid has support for almost all standard languages. but android is the one that passes the keys to it ( which an app developer needs to implement )
for now, the only vnc that has multi-language support is RealVNC

Check out this one:

- https://github.com/RandomCoderOrg/ubuntu-on-android/issues/93#issuecomment-1004252716
