### ISSUE TITLE
Broken PIP

### ISSUE THREAD

**Issue by BlackLordDSNR** [RandomCoderOrg/ubuntu-on-android#208]
![Screenshot_20221209_150153.jpg](https://user-images.githubusercontent.com/88499005/206708875-5aa4704a-ab82-46c7-8904-50ff9b200d19.jpg)![Screenshot_20221209_150204.jpg](https://user-images.githubusercontent.com/88499005/206708892-d5e61235-0e4f-4538-ad8d-225afa1eb27d.jpg)
Does anyone know, how to fix that?

**Comment by SaicharanKandukuri** [comment]
Try installing `python3-pip`
```bash
apt install python3-pip
```

**Comment by ask9027** [comment]
make backup of `/etc/profile.d/termux-proot.sh`
and remove it. then try to run `pip --version`.
