### ISSUE TITLE
Feature Request: How to cast the linux screen to TV?

### ISSUE THREAD

**Issue by nitinjs** [RandomCoderOrg/ubuntu-on-android#209]
How to miracast the linux screen?

Futuristic: 
1. TV as a remotely connected monitor via miracast
2. Bluetooth/RF keyboard and mouse connected to the linux 

```
1. android phone with linux as a CPU
2. BT/RF keyboard and mouse
3. TV as a monitor
4. Speakers? TV already has it
```

every android phone with Samsung dex but wireless, isn't it? 
![image](https://github.githubassets.com/images/icons/emoji/unicode/1f440.png)

**Comment by SaicharanKandukuri** [comment]
Nice Question @nitinjs 

Never tested `miracast` with udroid
But I can say it needs some pretty good effort and hacks to get everything working

<hr>

## Hacks available for now without miracast

- android phone with Linux as a CPU
> it's proot anyway

- BT/RF keyboard and mouse
> can be achievable in vnc apps like ( [avnc](https://f-droid.org/en/packages/com.gaurav.avnc/), [NetHunter kex app](https://store.nethunter.com/en/packages/com.offsec.nethunter.kex/) and etc ), but no direct access from OS

- TV as a monitor
> achievable with vnc arg `-localhost no` which makes vnc to available to every device in the local network ( which make a smart TV that could run a vnc client one of em )

- Speakers? TV already has it

> **Same**, need termux with some special commands to transmit audio through the local network so that termux or any pulse audio receiver client installed inside smart tv could receive and play audio

<hr>


> I'll start testing miracast soon

**Comment by nitinjs** [comment]
for kb/mouse maybe this can be done

<img src="https://user-images.githubusercontent.com/298479/211483204-e061108b-d6a5-44e3-92f4-92be4a244c22.png" width="30%" />

**Comment by SaicharanKandukuri** [comment]
> for kb/mouse maybe this can be done
> 
> <img src="https://user-images.githubusercontent.com/298479/211483204-e061108b-d6a5-44e3-92f4-92be4a244c22.png" width="30%" />
> 

I think usb over IP ( considering sending events directly to Linux ) just makes it more confusing cause there are two receivers ( Android & Linux )

**Comment by SaicharanKandukuri** [comment]
![image](https://user-images.githubusercontent.com/68287637/211526978-0ffb6879-978a-4b2f-ac0c-5332d79f3fbb.png)

VNC usually takes care of this job

**Comment by nitinjs** [comment]
It was already possible with Termux Proot/Chroot distros
[Install Ubuntu in Android, in Termux, using proot-distro](https://xdaforums.com/t/guide-no-root-how-to-install-debian-or-ubuntu-environments-on-android-in-termux-using-proot-distro.4570275/)

Installed proot distro Ubuntu in termux
Installed xrdp/vnc server

Installed RDP client on android
Got connected

Now phone acts as a CPU and TV acts as Monitor
Just the way I visualized

cheers
