### ISSUE TITLE
Blank Screen on VNC

### ISSUE THREAD

**Issue by brian200508** [RandomCoderOrg/ubuntu-on-android#215]
Hi all,

at first: great work 👍😀. Nevertheless I am struggling with the following issue: the VNC Viewer Shows only a blank screen after successful connection. 

What's wrong?

Steps to reproduce:
- install Termux 
- termux-setup-storage 
- pkg update
- . <(curl -Ls https://bit.ly/udroid-installer)
After successful install:
- udroid login jammy:xfce4
- vncserver :1

I have tested it on a Samsung Galaxy Fold 3 with Android 13.

See also attached screenshots. 

Best regards 
Brian 
![Screenshot_20230220_165921_Termux](https://user-images.githubusercontent.com/36002167/220155507-a7e82e77-664c-4fa5-94ca-48e763496758.jpg)
![Screenshot_20230220_170045_Termux](https://user-images.githubusercontent.com/36002167/220155514-4875ea66-7f4a-425e-9800-d956f50da9f8.jpg)
![Screenshot_20230220_170111_VNC Viewer](https://user-images.githubusercontent.com/36002167/220155519-cf8349cd-58c8-4d7f-ba99-c5122b3be276.jpg)
![Screenshot_20230220_170217_VNC Viewer](https://user-images.githubusercontent.com/36002167/220155522-61a87ed0-9f07-475d-b4a3-88c75c34e9ca.jpg)

**Comment by ghost** [comment]
so you're using Android 13, maybe it's phantom process killing the xfce while running, you can fix it via this
https://github.com/SaicharanKandukuri/termux-android12-phantom-fix

is it installed normally? have you tried updating/upgrading packages

try `tigervncserver -xstartup /usr/share/xfce4-session -geometry 1280x720`

also send logs from ~/.vnc/

**Comment by brian200508** [comment]
thanks for your quick response

Phantom Process Killer is disabled:

```
brian@localhost:~$ adb shell settings get global settings_enable_monitor_phantom_procs
false
brian@localhost:~$ 
```

alternative start of VNC server crashes too with the errors/log entries attached as screenshots
![Screenshot_20230220_195653_Termux](https://user-images.githubusercontent.com/36002167/220182202-d30933f7-fc95-48df-b31d-f1e9c38f30b4.jpg)
![Screenshot_20230220_195800_Termux](https://user-images.githubusercontent.com/36002167/220182207-9a1a4563-d74d-4ac8-a44a-ad051c816d83.jpg)
:

```
tigervncserver -xstartup /usr/share/xfce4-session -geometry 1280x720
```

**Comment by brian200508** [comment]
did an 

```
apt update
apt upgrade
exit
```

logged in again and started the VNC server again

looks like that there are some files missing... see attached screenshots
![Screenshot_20230220_200456_Termux](https://user-images.githubusercontent.com/36002167/220183321-5d0a2992-5a0c-4c96-abc1-e939d2f52e32.jpg)
![Screenshot_20230220_200523_Termux](https://user-images.githubusercontent.com/36002167/220183331-c9470598-2c46-4cdd-a8dd-5f035b56c73a.jpg)
![Screenshot_20230220_200708_Termux](https://user-images.githubusercontent.com/36002167/220183337-3ffb91b1-37ef-413d-b493-1771d923f1f6.jpg)

**Comment by ghost** [comment]
well, check is xfce4 installed
`ls /usr/bin/start*`

if there's something like `/usr/bin/startxfce4` in output, replace `xfce4-session` with `startxfce4`


it it doesn't works then reset rootfs with
`udroid reset jammy:xfce4`

**Comment by ghost** [comment]
> did an 
> 
> ```
> apt update
> apt upgrade
> exit
> ```
> 
> logged in again and started the VNC server again
> 
> looks like that there are some files missing... see attached screenshots
> ![Screenshot_20230220_200456_Termux](https://user-images.githubusercontent.com/36002167/220183321-5d0a2992-5a0c-4c96-abc1-e939d2f52e32.jpg)
> ![Screenshot_20230220_200523_Termux](https://user-images.githubusercontent.com/36002167/220183331-c9470598-2c46-4cdd-a8dd-5f035b56c73a.jpg)
> ![Screenshot_20230220_200708_Termux](https://user-images.githubusercontent.com/36002167/220183337-3ffb91b1-37ef-413d-b493-1771d923f1f6.jpg)
> 

apologies, replace `/usr/share/xfce4-session` with `/usr/bin/xfce4-session`

**Comment by brian200508** [comment]
VNC crashes with ```/usr/bin/xfce4-session```
VNC starts with ```/usr/bin/startxfce4```, but blank screen

can start applications (for example xterm
![Screenshot_20230220_202818_Termux](https://user-images.githubusercontent.com/36002167/220185790-9636c981-b6a1-4dab-b746-4b21f079ac7a.jpg)
![Screenshot_20230220_202824_VNC Viewer](https://user-images.githubusercontent.com/36002167/220185795-95b2bfae-bed2-4d8b-8da4-6762f3ee8714.jpg)
) when setting ```DISPLAY=:1```, but there is no desktop; see screenshots

**Comment by brian200508** [comment]
trying resetting rootfs...

**Comment by ghost** [comment]
have you enabled wake lock from notification of Termux, everything seems installed fine, it's only desktop crashing

alternatively you can start tigervncserver with /usr/bin/xterm, and inside the session you can start xfce with `startxfce4` in xterm.

**Comment by brian200508** [comment]
thanks for Your hints; I will try after resetting has been finished

**Comment by ghost** [comment]
crashing or blank screen problems are pretty much with newer android devices, there's ton of vendors and some problems can be vendor specific, Android isn't in favour of running such apps already with newer updates, things are getting limited than before.



there's `tigervnc` package too in Termux, you can use termux's native vnc to run proot apps/desktop
`pkg update`
`pkg install x11-repo`
`pkg install tigervnc xorg-xhost`

then start vnc server, after that type `xhost +` in same terminal

open proot in different session, export display with the started port

generally with different devices i tried, it was way more stable than proot's vnc, hope this works for you.

**Comment by brian200508** [comment]
ok, i will try this... thanks :)

yes, that might be possible; BTW.: I have the same issue with AndroNix

**Comment by ThatMG393** [comment]
Is it working now?

**Comment by brian200508** [comment]
No. I habe also tried RDP and Termux-X11 according to the Wiki documentation.

I habe attached the screenshots for Termux-X11.
![Screenshot_20230221_085154_Termux](https://user-images.githubusercontent.com/36002167/220282759-7ac13eaa-eebe-4c8f-afaf-2604e988c426.jpg)
![Screenshot_20230221_085242_TermuxX11](https://user-images.githubusercontent.com/36002167/220282776-fcae71a9-6d05-4505-a980-aa80410a8663.jpg)

**Comment by SaicharanKandukuri** [comment]
![image](https://user-images.githubusercontent.com/68287637/220283597-db9d0cec-1865-4f6c-ac18-fd2834b56ce4.png)

looks like `termux-x11` crashed

**Comment by brian200508** [comment]
Awesome WM works with VNC; see screenshots...
![Screenshot_20230221_112924_Termux](https://user-images.githubusercontent.com/36002167/220319776-3c75e80a-4b2e-456b-b238-c3660c9d3e9f.jpg)
![Screenshot_20230221_112646_VNC Viewer](https://user-images.githubusercontent.com/36002167/220319792-7ede96e3-c196-4f6e-b94f-0216bc767b10.jpg)

**Comment by brian200508** [comment]
Seems to be an device dependent (Samsung Galaxy Fold 3, Android 13, One UI 5.1) issue. For the next time it's OK, when I use Awesome only. I will try some weeks later again... ;)

If You want to, You can close this ticket.

Thanks for Your help and best regards
brian

**Comment by brian200508** [comment]
LXQT desktop works 😀

```
# LXQT desktop (works on Android 13)
echo "Setting up LXQT desktop..."
vncserver --kill :1
sudo apt remove -y xfce4
sudo apt install -y lxqt
# nano .vnc/xstartup
# #change:
# #dbus-launch --exit-with-session /usr/bin/startxfce4
# dbus-launch --exit-with-session /usr/bin/startlxqt
sed -i 's/startxfce4/startlxqt/' ~/.vnc/xstartup
vncserver :1
```
![Screenshot_20230309_150956_AVNC](https://user-images.githubusercontent.com/36002167/224050589-a276267c-ca6b-4ac4-bd9d-504be22e7c49.jpg)

Best regards 
Brian

**Comment by brian200508** [comment]
LXQT is fine for me; closing issue.
