### ISSUE TITLE
[ERROR] - Failed to install jammy:xfce4

### ISSUE THREAD

**Issue by neopromic** [RandomCoderOrg/ubuntu-on-android#216]
It's giving that error when I'm installing this in my termux, idk what I need to do to solve, anyone can help? Error:
/data/data/com  78%   1.30G  4.27MB/s    in 6m 0s
failed to download udroid-jammy-xfce4.tar.gz
[E] Failed to install jammy:xfce4

**Comment by ThatMG393** [comment]
Try do it manually,

`wget https://github.com/RandomCoderOrg/ubuntu-on-android/releases/download/v3/udroid-xfce4-impishTjammy-V3-maintainence-2-arm64.tar.gz`

**Comment by AnninoDr4** [comment]
its probably network issue or device storage space

use this to debug `udroid` and try to share screenshot
```bash
bash -x udroid install jammy:xfce4
```
