### ISSUE TITLE
Time to focus on quality features

### ISSUE THREAD

**Issue by AnninoDr4** [RandomCoderOrg/ubuntu-on-android#217]
looks like udroid finally reached to state to stop worrying about publishing root-filesystems ( Thanks to `udroid-download` and new * `fs-manager-udroid` )  so now we can focus on adding quality features to pre-builds like making use of termux & android api to supply more info to proot containers

It's time to make use of the features termux and android provide to improve user experience and document those features.

**Comment by ThatMG393** [comment]
I agree!

**Comment by ghost** [comment]
it is a good idea.

the current rootfs are similar to other linux on android utilities, made for android 9,10, to perform the best. what did you meant by quality rootfs? current ones are quality ones too.

while working on this thing, we should consider thinking about android thirteen, a lot of users are getting blank screen, regardless phantom process, maybe rootfs need some more work.

also updating wiki (that i will  start by the end of this month. again quality features? like pre installing some more apps, optimising rootfs would also work while that, reducing orphaned packages which wont ever been used in proot, it may make things fast (manually installing  each packages instead of meta package etc). 

we should continue this in discord i guess to get other users' feedback too over android 13 issues

**Comment by AnninoDr4** [comment]
> what did you meant by quality rootfs? current ones are quality ones too.

like 
- cherry-pick packages that work in proot
- document building process for pre-builds
- add build scripts for pre-builds ( @SaicharanKandukuri 👀 ) [ I'll try to add those if possible ]
- focus on support for general usage applications like browsers, IDE, and probably some image editors
- add/document some unique packages ( that are popular and usually don't work in android ( like web/Ai tools ) ) to attract users.
- build some apps that use termux-api's data and expose them to proot containers ( handy features )

> while working on this thing, we should consider thinking about android thirteen, a lot of users are getting blank screen, regardless phantom process, maybe rootfs need some more work.

need to try reproducing that issue

> also updating wiki (that i will start by the end of this month.

🥳

> again quality features? like pre installing some more apps, optimising rootfs would also work while that, reducing orphaned packages which wont ever been used in proot, it may make things fast (manually installing each packages instead of meta package etc).

Need to cherry-pick packages to remove

**Comment by ghost** [comment]
vnc wouldnt a good place with touch screen for image editors, what about moving to xrdp (with xvnc), it deems to work perfectly both inside termux and proot's xrdp package, with ms rdp it automatically configures to a ideal resolution and rotation support, i think there it may be more beneficial to have such apps (also direct touch support). lets add this and replace vnc for good

libreoffice to onlyoffice i guess 

> * add/document some unique packages ( that are popular and usually don't work in android ( like web/Ai tools ) ) to attract users.
popular suites of applications hmm,  it would be tricky, what about a base rootfs with most minimal applications set, and scripts to install other apps categorized, or special rootfs for office, web development, compilers, etc. storage is major concern, putting everything at once would look heavy

have you heard of virgl? for some adreno gpu it works perfectly in termux and possible GPU access

**Comment by ThatMG393** [comment]
@b1tchysam he's currently testing my script for gpu acceleration

https://github.com/SaicharanKandukuri/gpu_accel_termux

**Comment by ghost** [comment]
> @b1tchysam he's currently testing my script for gpu acceleration
> 
> https://github.com/SaicharanKandukuri/gpu_accel_termux

i havent tried that LOL, i meant with exagear virgl, it runs ubuntu and mashed up things

**Comment by ThatMG393** [comment]
@b1tchysam 
> > @b1tchysam he's currently testing my script for gpu acceleration
> > https://github.com/SaicharanKandukuri/gpu_accel_termux
> 
> i havent tried that LOL, i meant with exagear virgl, it runs ubuntu and mashed up things

Try it:
https://github.com/ThatMG393/gpu_accel_termux
