### ISSUE TITLE
Set vnc resolution as device's

### ISSUE THREAD

**Issue by mizzunet** [RandomCoderOrg/ubuntu-on-android#22]
**Is your feature request related to a problem? Please describe.**
It would be cool to use in landscape mode if the vnc fit to the screen of the phone

**Describe the solution you'd like**
Set VNC's resolution as device's 

**Describe alternatives you've considered**
I got my phone resolution from `dumpsys display` and changed VNC's from Settings

**Comment by SaicharanKandukuri** [comment]
I would suggest using [Nethunter KEX]( https://f-droid.org/app/com.offsec.nethunter.kex) or bvnc pro
This kind of vnc changes vnc resolution to match display resolution automatically
so no need of using `vncserver --geometry <width>x<height>`
And also it works great than normal vnc in most cases
If you turn of Full-screen bit mapping in settings

> Nethunter kex is available in [nethunter store](https://store.nethunter.com/en/)
> Bvnc pro is avalible in [playstore](https://play.google.com/store/apps/details?id=com.iiordanov.bVNC&hl=en_IN&gl=US)

**Comment by SaicharanKandukuri** [comment]
https://user-images.githubusercontent.com/68287637/122855023-33740880-d332-11eb-806a-8cd804559f6b.mp4

You can see it in this sample video the second you enter nethunter vnc it changes to device screen resolution
apps like Nethunter Kex can contact vnc service to change resolution
whereas RealVNC can't
> Don't take the last seconds of video I was doing other things #

**Comment by mizzunet** [comment]
Awesome 👍
