### ISSUE TITLE
focal:xfce4 apt update 404 not found

### ISSUE THREAD

**Issue by wangerzi** [RandomCoderOrg/ubuntu-on-android#221]
I'm trying to use focal:xfce4, because I feeling focal is faster than jammy:xfce4 and jammy:xfce4 firefox browser always crash for me, then I exec `apt update` in terminal, got this problem:

![image](https://user-images.githubusercontent.com/22190579/229419515-5c19c051-1de8-4a28-aedc-0891379fe47c.png)

Phone model: https://www.gizmochina.com/product/meizu-16th-plus/

I am also looking for a related solution, if I find a usable apt source will update here

**Comment by SaicharanKandukuri** [comment]
> I'm trying to use focal:xfce4, because I feeling focal is faster than jammy:xfce4 and jammy:xfce4 firefox browser always crash for me, then I exec apt update in terminal, got this problem:

`hirsure` got deprecated
Changing `apt` sources list could help solve the issue
Try this fix 
```bash
sed -i 's/hirsute/focal/g' sources.list;
```

**Comment by wangerzi** [comment]
@SaicharanKandukuri 

It's work!!! `apt update` can be executed normally, but I got the following error when I install or upgrade package:

> E: Unable to correct problems, you have held broken packages.

![image](https://user-images.githubusercontent.com/22190579/229455452-80d7e514-891c-4d5a-a369-d4a93c69b1e1.png)
![image](https://user-images.githubusercontent.com/22190579/229455828-fd502080-b23d-4a7e-84df-e68471ca60e6.png)

I must use aptitude and resolve conflict manually to upgrade or install some package.
It would be great if there is a way to avoid these errors, so that it will be less confusing to use.

![image](https://user-images.githubusercontent.com/22190579/229464030-7730f372-bb9b-49a9-9351-9627937ff36c.png)

**Comment by c4ttysam** [comment]
do `apt -f install`

**Comment by wangerzi** [comment]
I tried this and it's worked:
```bash
sed -i 's/ports\.ubuntu\.com/old-releases.ubuntu.com/g' sources.list
sed -i 's/\/ubuntu-ports/\/ubuntu/g' sources.list
```

means: 
> deb http://ports.ubuntu.com/ubuntu-ports hirsute main restricted
to
> deb http://old-releases.ubuntu.com/ubuntu hirsute main restricted
