### ISSUE TITLE
Can't start ubuntu

### ISSUE THREAD

**Issue by Origins-Eternity** [RandomCoderOrg/ubuntu-on-android#224]
I installed ubuntu successfully but I can't start it. 
![Screenshot_2023-04-30-17-27-00](https://user-images.githubusercontent.com/63846610/235345863-9ad2d8ae-033b-4b0f-af8e-3531ea361a20.png)
OS: Android 6 (Non-root)
Termux: 0.118.0+93eafff

**Comment by ThatMG393** [comment]
Can you try running `proot`?

Just type `proot` on the terminal

**Comment by Origins-Eternity** [comment]
![Screenshot_2023-05-01-06-48-09](https://user-images.githubusercontent.com/63846610/235380089-151799b0-30a7-48ef-8521-6fc776c179e6.png)
![Screenshot_2023-05-01-06-46-57](https://user-images.githubusercontent.com/63846610/235380093-0673c1f8-2979-409b-8fe3-3ebd11791906.png)

**Comment by ThatMG393** [comment]
It seems like you installed Termux from G-Play, it's deprecated download one at [F-Droid](https://f-droid.org/en/packages/com.termux/) or [Github](https://github.com/termux/termux-app)

**Comment by ThatMG393** [comment]
You installed Termux from Google Play. It's deprecated now. Download one at [F-Droid](https://f-droid.org/en/packages/com.termux/) or [Github](https://github.com/termux/termux-app) or [Github Actions](https://github.com/termux/termux-app/actions/workflows/debug_build.yml)

**Comment by Origins-Eternity** [comment]
The latest successful version on GitHub actions is here: https://github.com/termux/termux-app/actions/runs/4844403329 So should I try this version?

**Comment by SaicharanKandukuri** [comment]
You can 👍

**Comment by Origins-Eternity** [comment]
It still doesn't work 😭
![Screenshot_2023-05-01-15-25-06](https://user-images.githubusercontent.com/63846610/235422777-46f5656b-83e7-429f-8f5d-dfb83ef3bbbf.png)

**Comment by SaicharanKandukuri** [comment]
![s](https://user-images.githubusercontent.com/68287637/235424163-fccab69e-a22d-4f36-9e06-c07621f82eee.jpg)

i had the same termux
try to check `termux-info` version codes with my screenshots

> if your previous termux app is not from github then you should uninstall the previous termux version before installing the new one from GitHub

**Comment by Origins-Eternity** [comment]
![Screenshot_2023-05-01-15-51-55](https://user-images.githubusercontent.com/63846610/235425345-cebcaf47-9464-4752-9255-9bf11b2e977a.png)
![Screenshot_2023-05-01-15-56-45](https://user-images.githubusercontent.com/63846610/235425890-5894e514-a932-42ac-a5aa-93e6ebf7b214.png)
I do uninstall the old version before installing a new one.

**Comment by ThatMG393** [comment]
Maybe it's because of your API level

**Comment by Origins-Eternity** [comment]
What does it mean?

**Comment by SaicharanKandukuri** [comment]
@Origins-Eternal 
It looks like your sources list has unmaintained sources even if you updated that app?
![image](https://user-images.githubusercontent.com/68287637/235428965-1d6f9acc-750a-45e0-90ae-c93ac3a18fdc.png)

IDK for sure why this happened but here is a workaround worth a try
we can force upgrade all packages by changing sources to `termux-main`
```bash
echo "deb https://packages-cf.termux.org/apt/termux-main/ stable main" > ${PREFIX}/etc/apt/sources.list
apt update
apt full-upgrade
```

**Comment by Origins-Eternity** [comment]
![Screenshot_2023-05-01-16-46-00](https://user-images.githubusercontent.com/63846610/235430758-ccdefd14-eb66-486c-8c58-dac3b07f9a47.png)

**Comment by SaicharanKandukuri** [comment]
wait that's odd

try again
```bash
echo "deb https://packages-cf.termux.org/apt/termux-main/ stable main" > ${PREFIX}/etc/apt/sources.list
apt full-upgrade
```

**Comment by ThatMG393** [comment]
`proot` implemented/used some features/API that is not available for Android 6, that's why I said earlier that it might be about your API level

**Comment by c4ttysam** [comment]
although both Android versions support but packages aren't updated

there's apt-android-5 artifact from cl builds for Android 5-6
https://github.com/termux/termux-app/actions/workflows/debug_build.yml?query=branch%3Amaster+

these are the updated repo compatible with 5/6 it uses
```
deb https://packages.termux.dev/apt/termux-main-21 stable main
deb https://termux.dev/science-packages-21-bin science stable
deb https://termux.dev/game-packages-21-bin games stable
deb https://termux.dev/termux-root-packages-21-bin root stable
```

until the 0.119 releases. 

kinda experimental, it may not work with udroid since nobody's there to test that old Android versions and the problem is with termux packages for older version

**Comment by c4ttysam** [comment]
so no new packages for Android 5/6, we can't help with this, there are outdated packages. you should consider using another device
