### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by GDPlayer** [RandomCoderOrg/ubuntu-on-android#225]
```
> INSTALL
[✔] Fetching distro data..
ERROR:
link not found for :
either the suite or varient is not supported or invalid options supplied
Report this issue at https://github.com/RandomCoderOrg/ubuntu-on-android/issues
[I] ⋊> ~
```
shell: fish
android: 11

**Comment by ThatMG393** [comment]
Can't install what?

**Comment by GDPlayer** [comment]
cant install distro- goddamnit they closed this

**Comment by whyimlonely** [comment]
> cant install distro- goddamnit they closed this

you haven't replied for like 2-3 weeks, enough to close the issue.

try

`udroid upgrade`

then use `udroid list` to check available version and install with

`udroid install version:de`
