### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by sunmughan** [RandomCoderOrg/ubuntu-on-android#226]
![Screenshot_20230602_004606](https://github.com/RandomCoderOrg/ubuntu-on-android/assets/18499082/838b8bb2-c918-43f5-b52b-104b0cd8721b)

Please check this error. And guide me to fix it.

**Comment by idkwhyisit** [comment]
hi
what device are you using? and from where you downloaded the termux, also is the initial installation done?

**Comment by sunmughan** [comment]
> hi what device are you using? and from where you downloaded the termux, also is the initial installation done?

My device is samsung Galaxy Note 10
I've downloaded this termux from its latest F-Droid repo.
Yes the initial installation is done. Just the last step "**udroid install jammy:xfce4**" is creating this error.

**Comment by sunmughan** [comment]
> hi what device are you using? and from where you downloaded the termux, also is the initial installation done?

My device is samsung Galaxy Note 10
I've downloaded this termux from its latest F-Droid repo.
Yes the initial installation is done. Just the last step "**udroid install jammy:xfce4**" is creating this error.

**Comment by whyimlonely** [comment]
strange, some commands are missing
can you try the action builds (Android 7 ones) from there
https://github.com/termux/termux-app/actions/runs/5078496493
instead of f droid builds

**Comment by sunmughan** [comment]
I tried following from scratch using the fresh build of termux from the link you shared. And guess what... the results are still the same. Idk why is this happening. But it feels wierd.

Earlier I've enjoyed Ubuntu on Android on my last 5 phones smoothly. This one creating mess.

![Screenshot_20230603-001600_Termux](https://github.com/RandomCoderOrg/ubuntu-on-android/assets/18499082/de0bf145-e6cb-4454-bd87-f46772a02ac6)

**Comment by ThatMG393** [comment]
Try installing the `universal` build of Termux, also I think that issue can be solve by running `udroid --update-cache`

**Comment by sunmughan** [comment]
Tried. Still getting the same result.

**Comment by SaicharanKandukuri** [comment]
Try this manual fix
```bash
udroid upgrade
curl -L -o /data/data/com.termux/files/usr/etc/udroid/.cache/distro-data.json.cache https://raw.githubusercontent.com/RandomCoderOrg/udroid-download/main/distro-data.json
```

**Comment by ThatMG393** [comment]
Is it fixed yet?
