### ISSUE TITLE
Make a version for rooted users

### ISSUE THREAD

**Issue by rlukas210** [RandomCoderOrg/ubuntu-on-android#23]
I know about the support is mainly for proot users, but i'm suggesting a version for root users;
I can help testing or with another things (such as setup, write Scripts, etc)

**Comment by SaicharanKandukuri** [comment]
Things get betters with there are testers and helpers
if there are enough heartful testers and devs who could help me out and work together in writing scripts and Algos and testing out things then sure we can make and upload it

**Comment by SaicharanKandukuri** [comment]
One man for such complicated thing(cause its root) may lead to really bad things

**Comment by rlukas210** [comment]
I'm begginer with bash, but i learn +- fast
I'll fork and try to make an script (download the rootfs and extract, mount and run and possibly detect If required paths such as /dev /proc /sys are mounted or not)
And tomorrow or after tomorrow i'll do an PR

**Comment by SaicharanKandukuri** [comment]
Nope I decided this repo is for non-root users only so it has to be separated

**Comment by rlukas210** [comment]
#17 i have an issue too (not same as 17); i have created a non root user (in proot-distro), tried to start vnc but only a white screen with an error message appears, It may be happening due a non LTS version of ubuntu

**Comment by rlukas210** [comment]
> Nope I decided this repo is for non-root users only so it has to be separated

Okay

**Comment by SaicharanKandukuri** [comment]
Join my Discord server for further discussion on root

**Comment by rlukas210** [comment]
> Join my Discord server for further discussion on root

Joined
