### ISSUE TITLE
Terminal and file manager is not opening on x-11 on rootuser. Unable to run non-root on x-11.

### ISSUE THREAD

**Issue by JacenBridger** [RandomCoderOrg/ubuntu-on-android#230]
Hello, I have managed to get run udroid on x-11.
But the file manager, terminal and other things is not opening. Here are some pictures.
![IMG_20230709_115233](https://github.com/RandomCoderOrg/ubuntu-on-android/assets/110893579/b5ef27e0-df5e-4288-90fd-8ed2855e37c4)
![IMG_20230709_115255](https://github.com/RandomCoderOrg/ubuntu-on-android/assets/110893579/37ececfa-c111-4263-b7e8-06a5ff8923b5)

So, how to fix that ?

I have added a non-root user. Below are the commands i have tried to run for x-11 but it crashes the termux app because of multiple code failure.

export DISPLAY=:0
termux-x11 :0 &
udroid login jammy:xfce4
su trishul
export DISPLAY=:0
dbus-launch --exit-with-session startxfce4

So, how to run non-root user in x-11?

**Comment by ThatMG393** [comment]
Don't set the DISPLAY variable outside of the proot.
If you're using display `:0` dont set it, just run `termux-x11` it automatically defaults to display `:0`.
Use `login trishul` instead of `su trishul` then `export DISPLAY=:0 && dbus-launch --exit-with-session startxfce4`

**Comment by JacenBridger** [comment]
Thank you.
I managed to work it somehow.
Honourable mention:@ThatMG393 and [this discussions ](https://github.com/orgs/RandomCoderOrg/discussions/152)

**Comment by JacenBridger** [comment]
Closing this issue

**Comment by JacenBridger** [comment]
Closing this issue

**Comment by RebornOfc** [comment]
I would like to re-open this because no actual working solution has been provided (for my case), and I am having literally the same problem on jammy:xfce4, but using the provided VNC server instead.

Edit: If anyone come across this in the future, see my solutions below.

**Comment by RebornOfc** [comment]
Hello, doing this could solve the (terminal) problem for me:

![image](https://github.com/RandomCoderOrg/ubuntu-on-android/assets/89420126/43847f82-c156-4aab-a11b-56a609592675)

Now choose any terminal here and be happy

![image](https://github.com/RandomCoderOrg/ubuntu-on-android/assets/89420126/a5885f70-7521-44d8-90bb-91764e270e0c)

**Comment by RebornOfc** [comment]
For the file explorer problem I just installed another by typing:

apt-get install nautilus

Then just opening it by typing:

nautilus
