### ISSUE TITLE
Hardware Acceleration?

### ISSUE THREAD

**Issue by jeffdumcum** [RandomCoderOrg/ubuntu-on-android#235]
Is there any way to get hardware acceleration on Udroid?

**Comment by jeffdumcum** [comment]
I'm on a tensor G1 if that matters

**Comment by SaicharanKandukuri** [comment]
Guess there are no hardware Acceleration methods for Exynos varients including Tensor G1

**Comment by jeffdumcum** [comment]
Unrelated, but I am having an error where it says can't open display 0 
libmutter-Message: 18:39:01.701: Running GNOME Shell (using mutter 45.0) as a X11 window and compositing manager
Failed to setup: Unable to open display ':0'
![Screenshot_20231021-134019](https://github.com/RandomCoderOrg/ubuntu-on-android/assets/105110025/a12f5357-e2b9-4c05-aced-a288c38f0ba3)

**Comment by 23xvx** [comment]
> Unrelated, but I am having an error where it says can't open display 0 
> libmutter-Message: 18:39:01.701: Running GNOME Shell (using mutter 45.0) as a X11 window and compositing manager
> Failed to setup: Unable to open display ':0'
> ![Screenshot_20231021-134019](https://github.com/RandomCoderOrg/ubuntu-on-android/assets/105110025/a12f5357-e2b9-4c05-aced-a288c38f0ba3)
> 

If you are using vnc 
DISPLAY variable should be 1

**Comment by jeffdumcum** [comment]
I am using X11

**Comment by jeffdumcum** [comment]
Even when i switch the display variable to 1 it still does not work

**Comment by jeffdumcum** [comment]
Even when I switch it to a different number it still doesnt work

**Comment by 23xvx** [comment]
> Even when I switch it to a different number it still doesnt work

Make sure you have started termux-x11 correctly 
Also if you are using proot-distro 
Login with --shared-tmp

**Comment by mintdotco** [comment]
proot-distro doesn’t work anymore

**Comment by jeffdumcum** [comment]
If anyone has a solution please tell me

**Comment by SaicharanKandukuri** [comment]
try `DISPLAY=:0 gnome-shell --x11`

**Comment by SaicharanKandukuri** [comment]
> I'm on a tensor G1 if that matters

I own a tensor G1 device but It's not with me right now,
I will start testing on it after this month

**Comment by jeffdumcum** [comment]
> > I'm on a tensor G1 if that matters
> 
> I own a tensor G1 device but It's not with me right now, I will start testing on it after this month

Thanks, would love if you could test that

**Comment by jeffdumcum** [comment]
> try `DISPLAY=:0 gnome-shell --x11`

Fixed it because the instructions that were for installing mantis were incorrect

**Comment by SaicharanKandukuri** [comment]
> > try `DISPLAY=:0 gnome-shell --x11`
> 
> Fixed it because the instructions that were for installing mantis were incorrect

I planned to rewrite udroid after this month
I'll fix wiki & documentation issues
