### ISSUE TITLE
xfce crashes or fails to start, various errors

### ISSUE THREAD

**Issue by vanarok** [RandomCoderOrg/ubuntu-on-android#239]
What I'm doing:
```
apt update && apt install git -y
git clone https://github.com/RandomCoderOrg/fs-manager-udroid
cd fs-manager-udroid
bash install.sh
```
```
udroid install jammy:xfce4
udroid login jammy:xfce4
```
```
termux-x11 :0 &
```
```
udroid login jammy:xfce4 
```
```
export DIPLAY=:0
startxfce4
```
and I get the output:
```
/usr/bin/startxfce4: Starting X server

(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE)
```
я удаляю .X0-lock и еще раз запускаю:
```
[config] failed to pre-init udev

X.Org X Server 1.21.1.3
X Protocol Version 11, Revision 0
Current Operating System: Linux localhost 5.4.2-proot-facked #1 SMP PREEMPT Thu Feb 9 13:08:46 UTC 2023 aarch64
xorg-server 2:21.1.3-2ubuntu2.5 (For technical support please see http://www.ubuntu.com/support)
Current version of pixman: 0.40.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sun Dec 10 09:46:40 2023
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.
```

I managed to start it once, saw the desktop, but it immediately crashed out and never started again.

**Comment by vanarok** [comment]
![Uploading Screenshot_2023-12-10-15-52-59-163_com.kiwibrowser.browser-edit.jpg…]()

**Comment by vanarok** [comment]
https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/setting-up-gui/termux-x11
![Screenshot_2023-12-10-15-52-59-163_com kiwibrowser browser-edit](https://github.com/RandomCoderOrg/ubuntu-on-android/assets/6105977/cb93166c-3cc2-4c99-bf7f-6537ed05c9b6)

**Comment by 23xvx** [comment]
> https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/setting-up-gui/termux-x11 ![Screenshot_2023-12-10-15-52-59-163_com kiwibrowser browser-edit](https://private-user-images.githubusercontent.com/6105977/289350104-cb93166c-3cc2-4c99-bf7f-6537ed05c9b6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDY2MTYsIm5iZiI6MTcwMjIwNjMxNiwicGF0aCI6Ii82MTA1OTc3LzI4OTM1MDEwNC1jYjkzMTY2Yy0zY2MyLTRjOTktYmY3Zi02NTM3ZWQwNWM5YjYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTEwNTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmFlNjBiNTljZGIwNjA4MTVhZTU4ZTZjOGZiY2MwODNjMjUzZDAyOGQ1MTRmZTFhYjA1M2U0MWU3N2MxMTEwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V7jo26a2zLTx0vplppB-uk9qr7_M2in4aOU2b6K1T0w)

This is a typo 
It should be DISPLAY instead of DIPLAY
Show just use this to start xfce 
``` bash
export DISPLAY=:0
startxfce4
