### ISSUE TITLE
Can i use this a mini-PC?

### ISSUE THREAD

**Issue by mizzunet** [RandomCoderOrg/ubuntu-on-android#24]
I wonder, can I use physical mouse and keyboard with OTG USB?

**Comment by SaicharanKandukuri** [comment]
Yes you can in vnc in apps like nethunter kex I've tested in it
But it won't get into Linux the vncserver apps just tracks the actual cursor and synchronizes with the vnc cursor

**Comment by SaicharanKandukuri** [comment]
and keyboard works too.

**Comment by mizzunet** [comment]
Cool :D
