### ISSUE TITLE
How to actually install

### ISSUE THREAD

**Issue by Nyanana** [RandomCoderOrg/ubuntu-on-android#241]
Hello

Installation instructions here are clearly aimed at tech nerds

Can you please provide actuall installation instructions for us plebians

For example, where tf are you proposing we enter these terminal commands, on our android tablet, obvious to you, to me, no lmao

Please make it easy, not all of us are linux users

TY

**Comment by SaicharanKandukuri** [comment]
Well, pointed considered

**Comment by vsaucing** [comment]
. <(curl -Ls https://bit.ly/udroid-installer)

Copy the code and paste and run
