### ISSUE TITLE
android13 crush issues YT link is down

### ISSUE THREAD

**Issue by swk3087** [RandomCoderOrg/ubuntu-on-android#249]
![Screenshot_20241222-115656](https://github.com/user-attachments/assets/661666d4-1b1b-42b9-94a2-79e90cc388ee)

https://youtu.be/GCK@ghlyXSs?si=fVGAUDGKS LAPS

this link is down

**Comment by SaicharanKandukuri** [comment]
@swk3087 thanks for reporting this. I update the link at https://github.com/RandomCoderOrg/fs-manager-udroid/commit/

Here is the update link: https://youtu.be/GCN0gh1yXSs?si=qvqUWisk0gLHqXqs
