### ISSUE TITLE
Sound is not playing

### ISSUE THREAD

**Issue by mizzunet** [RandomCoderOrg/ubuntu-on-android#26]
![Screenshot_20210626-173545](https://user-images.githubusercontent.com/10193999/123512426-0c586680-d6a5-11eb-9af0-fcfe5e3531aa.png)

`pulseserver-start not found` 

So ran 
`pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
`

**Comment by SaicharanKandukuri** [comment]
Look like everything started successfully but.
can you give more
like
- from which app or instance the sound is not coming  from 
- is it for one app or you can't get sound from or full distro/session
- is sound worked before

**Comment by mizzunet** [comment]
1. YouTube from Firefox
2. Let me try to download and play a video
3. No

**Comment by SaicharanKandukuri** [comment]
by looking at pic looks like the distro did its job binding with termux PulseAudio may it's from termux end or some hidden setting

**Comment by mizzunet** [comment]
It's working on a different program(played MP3 song) lol

**Comment by SaicharanKandukuri** [comment]
Join our discord server for an extended chat and the latest updates on this project and my work

![Support Server](https://img.shields.io/discord/851345998831157288.svg?label=Discord&logo=Discord&colorB=7289da&style=for-the-badge) https://discord.gg/5BY2yh9Sfj

**Comment by mizzunet** [comment]
👍
