### ISSUE TITLE
[!] Sorry, but distribution download URL is not defined for CPU architecture 'armv8l'.

### ISSUE THREAD

**Issue by Wtab** [RandomCoderOrg/ubuntu-on-android#27]
I keep on getting this error when i run proot-distro install hippo.

**Comment by SaicharanKandukuri** [comment]
Hippo build for armhf devices not released yet
But is releasing soon

Join our discord server for updated info
https://discord.gg/y432PhPYCS

https://discord.com/channels/851345998831157288/857209836135120936/859090234108674108
