### ISSUE TITLE
E: Unable to determine file size for fd 4 - fstat (1: Operation not permitted) E: The package lists or status file could not be parsed or opened.

### ISSUE THREAD

**Issue by Wtab** [RandomCoderOrg/ubuntu-on-android#31]
I keep on getting this error.
![Screenshot_20210702-212837_Termux](https://user-images.githubusercontent.com/82286604/124339453-98bec980-db7c-11eb-9c0c-e5057dfc1b13.jpg)
I want to install sudo with (apt install sudo) but it this error at the title came.
i did (hippo upgrade) but it upgraded nothing.
please help i always wanted to get hippo on android, i been suffering.

**Comment by SaicharanKandukuri** [comment]
can you the output of `termux-info`

**Comment by SaicharanKandukuri** [comment]
and also try doing
`sudo chmod 777 -R /tmp`
if the problem persists then wipe the `/tmp` folder
`rm -rvf /tmp/*`

**Comment by Wtab** [comment]
Ok sorry for late respond i was sleeping.
Application version:
0.114
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
# sources.list.d/list.list
deb https://termux.xeffyr.ml/ extra main x11
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.177-21910157 #1 SMP PREEMPT Mon Jun 14 21:37:50 +07 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T510
Also im gonna try that method

**Comment by Wtab** [comment]
It's still not working 
![Screenshot_20210703-132731_Termux](https://user-images.githubusercontent.com/82286604/124362391-78395280-dc02-11eb-81fb-3c83ce4e21b6.jpg)

**Comment by SaicharanKandukuri** [comment]
Strange!

can you share outs of
`ls -la /dev/fd`
`ls -la /proc/self/fd`

**Comment by Wtab** [comment]
![Screenshot_20210703-140505_Termux](https://user-images.githubusercontent.com/82286604/124363162-b127f600-dc07-11eb-8590-efa5b5afd8ec.jpg)

**Comment by Wtab** [comment]
Nvm i got the bug fixed.

**Comment by SaicharanKandukuri** [comment]
@Wtab can you explain how you did it
i cant trace this problem cause `armhf` build is not tested
and i don't have `armhf` device
