### ISSUE TITLE
Vnc from PC

### ISSUE THREAD

**Issue by Tdawgg777** [RandomCoderOrg/ubuntu-on-android#32]
I have Hippo installed and can connect via VNC on my device, but how can I connect via my PC? New to all this, pretty sure I can edit xstartup but I need some assistance with that.

**Comment by SaicharanKandukuri** [comment]
Sure!

**Comment by SaicharanKandukuri** [comment]
which part do you need help with?

**Comment by Tdawgg777** [comment]
Thank for quick reply! I'm trying to connect to Hippo from my of but when I enter the up and port I get nothing... using real vnc viewer on windows 10... I thought I could edit xstartup to add option to export over network not only via localhost

**Comment by SaicharanKandukuri** [comment]
# here is my explanation to make it work!

![image](https://user-images.githubusercontent.com/68287637/124360983-4815a200-dc4a-11eb-8ffe-dd03407941e4.png)

> you can find the IPV4 ADDRESS with the command `hostname -I` 

## Here are some rules
- Both devices should be connected to the same hotspot/Router
- Don't enable firewalls or just configure them
<hr>

Device 1 - let's think your device IPV4 Adress where hippo installed is `193.XXX.XX.X`
Device 2 - and IVP4 of the device where you want to see the VNC is `192.XXX.XX.X` 

you can open vnc of hippo in Device 2 by entering the IPV4 address of Device 1 in device 2
so the address you should in device 2 to open VNC would be `193.XXX.XX.X:rfb_port_number<or>displaynumber`

This may help you
