### ISSUE TITLE
X connection to :1 broken (explicit kill or server)

### ISSUE THREAD

**Issue by Wtab** [RandomCoderOrg/ubuntu-on-android#33]
![Screenshot_20210703-194805_Termux](https://user-images.githubusercontent.com/82286604/124369232-9a00fc80-dc37-11eb-900a-0ffae6b0c977.jpg)
Once i ran the (vncserver) i got this message

**Comment by SaicharanKandukuri** [comment]
?

**Comment by stopka-html** [comment]
so the problem itself

**Comment by stopka-html** [comment]
This is due to a new user

**Comment by SaicharanKandukuri** [comment]
need to fix this confustion in next update
