### ISSUE TITLE
Can't use apt-get

### ISSUE THREAD

**Issue by Kronos256** [RandomCoderOrg/ubuntu-on-android#34]
I have some problems when I try installing libgles-dev, or anything for that matter. Maybe I am doing something wrong since I am new to Termux.

I always get this error:

Reading package lists... Error!
E: Unable to determine file size for fd 6 - fstat (1: Operation not permitted)
E: The package lists or status file could not be parsed or opened.

Here is what I get:

`~ $ hippo
root@localhost:~# apt-get install libgles-dev
Reading package lists... Error!
E: Unable to determine file size for fd 6 - fstat (1: Operation not permitted)
E: The package lists or status file could not be parsed or opened.
root@localhost:~# apt-get autoremove
Reading package lists... Error!
E: Unable to determine file size for fd 6 - fstat (1: Operation not permitted)
E: The package lists or status file could not be parsed or opened.
root@localhost:~# sudo apt-get install libgles-dev
sudo: unable to determine tty: Permission denied
Reading package lists... Error!
E: Unable to determine file size for fd 6 - fstat (1: Operation not permitted)
E: The package lists or status file could not be parsed or opened.
root@localhost:~# apt install libgles-dev
Reading package lists... Error!
E: Unable to determine file size for fd 6 - fstat (1: Operation not permitted)
E: The package lists or status file could not be parsed or opened.
root@localhost:~#`

**Comment by SaicharanKandukuri** [comment]
Try to do 
`apt clean`

**Comment by ghost** [comment]
can you try `apt update / apt-get update`, seems problem is while writing to `/tmp`. removing and recreating should work

**Comment by Randomae** [comment]
I had the issue on armf and apt clean worked

**Comment by Randomae** [comment]
it happened to me on armf
![Screenshot_20210704_090547_com termux](https://user-images.githubusercontent.com/86123055/124386155-1121a980-dca7-11eb-8677-5cf3a4ab2df9.jpg)

**Comment by SaicharanKandukuri** [comment]
does `apt clean` worked

**Comment by Randomae** [comment]
No

**Comment by SaicharanKandukuri** [comment]
can you share output of `termux-info`

**Comment by Randomae** [comment]
Application version:
0.114
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Fri Mar 5 12:01:24 CST 2021 armv8l Android
Device manufacturer:
HUAWEI
Device model:
MRD-LX3

**Comment by Wtab** [comment]
I think because apt does not has any permission or other thing like tar and tigervnc, i have that issue to.

**Comment by Wtab** [comment]
I think this will help
sudo chmod 777 -R /

**Comment by Kronos256** [comment]
> I think this will help
> sudo chmod 777 -R /

I already tried that but it didn't do anything,

**Comment by Kronos256** [comment]
apt clean  ; apt update ; pkg update they didn't help on armhf
![Screenshot_20210705-141225](https://user-images.githubusercontent.com/48557552/124469967-4ad3dc80-dd9b-11eb-97da-d205fe15f7f1.png)

**Comment by SaicharanKandukuri** [comment]
i look into this problem

**Comment by Randomae** [comment]
Kronos is right none of these work

**Comment by Wtab** [comment]
Maybe proot can't sanitize the binding  /proc/self/fd/0

**Comment by SaicharanKandukuri** [comment]
i made some 1st tests of armhf build
i didn't got any fd error😕
![Screenshot_20210706-085039_Termux (1)](https://user-images.githubusercontent.com/68287637/124549845-60094380-de4d-11eb-8109-b55d2958a732.jpg)

**Comment by Randomae** [comment]
Im testing if installing termux ver 116 helps

**Comment by SaicharanKandukuri** [comment]
@Randomae @Kronos256 tested v0.116 but the results are same
https://discord.com/channels/851345998831157288/851345999645507620/861884998499172393

**Comment by Randomae** [comment]
Bruh
I ![Screenshot_20210706_081059_com.termux.jpg](https://user-images.githubusercontent.com/86123055/124597682-c2ece180-de31-11eb-9c74-70401cdba364.jpg)

**Comment by Kronos256** [comment]
> Bruh

@Randomae
it's normal do nano /data/data/com.termux/files/usr/etc/proot-distro/hippo.sh
and remove # in front of those lines 
![Capture d’écran 2021-07-06 141652](https://user-images.githubusercontent.com/48557552/124598387-d49bac80-de64-11eb-87e0-205957840988.png)

**Comment by Randomae** [comment]
Installing

**Comment by Randomae** [comment]
the same error happens

**Comment by Allan-sketch** [comment]
Bro try :
$pkg install nano
$apt edit-sources main,root,X11,game,science

**Comment by Randomae** [comment]
In what could that help

**Comment by SaicharanKandukuri** [comment]
@Randomae  can you do it like
in termux install strace
```
apt install strace
```
in hippo
```
touch trace.txt
strace -o trace.txt apt update
```
and share `trace.txt` file here or discord
this provides extra info on what really happening

**Comment by Randomae** [comment]
I cant pass the file with the whole log but after the command this happened![Screenshot_20210708_083517_com.termux.jpg](https://user-images.githubusercontent.com/86123055/124922381-70ddc480-dfc7-11eb-8b87-dc68fc8e48b3.jpg)

**Comment by SaicharanKandukuri** [comment]
I am dumping `armhf` build to ubuntu 20

**Comment by Randomae** [comment]
Its ok

**Comment by SaicharanKandukuri** [comment]
https://discord.com/channels/851345998831157288/851345999645507620/867788172389253140

**Comment by SaicharanKandukuri** [comment]
> I am dumping `armhf` build to ubuntu 20

Look's like we need to accept the fact that termux and proot are still in active development!
and the issue in termux/proot is stale. so ubuntu 20 will be active for `armhf` until I get a fix

**Comment by SaicharanKandukuri** [comment]
No don't

**Comment by SaicharanKandukuri** [comment]
.

**Comment by SaicharanKandukuri** [comment]
looks like the problem is solved closing this issue
https://github.com/termux/proot/issues/172
