### ISSUE TITLE
Hippo install failing with "WARNING: linker:..."

### ISSUE THREAD

**Issue by lmservas** [RandomCoderOrg/ubuntu-on-android#35]
Was successful until I reached the Hippo command and then have been met with the following (gave it a couple retrys):

Installing hippo...........
[*] Installing hippo...
[*] Using cached rootfs tarball...
[*] Checking integrity, please wait...
[*] Extracting rootfs, please wait...
WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"

Seems to just freeze the instance indefinitely. Sorry for the inconvenience and thanks in advance for your time!

**Comment by SaicharanKandukuri** [comment]
can you share the output of `termux-info`

**Comment by lmservas** [comment]
Absolutely, output is:

Application version:
0.116
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.228-g609f9e512cd4-ab7337579 #1 SMP PREEMPT Wed May 5 05:16:48 UTC 2021 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 4 XL

**Comment by SaicharanKandukuri** [comment]
>WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"

These error logs came from tar 
and `/linkerconfig/ld.config.txt` this is not common
try using `hippo` in a new session
or reinstall termux

**Comment by lmservas** [comment]
Guessing it had something to do with the custom debug version of Termux I was using at the time. Rolled back to .114 and with fresh install all is well. Thank you!
