### ISSUE TITLE
hippo startvnc returns proot-distro should not be used as root

### ISSUE THREAD

**Issue by tiptruck** [RandomCoderOrg/ubuntu-on-android#36]
![SmartSelect_20210706-171042_Termux](https://user-images.githubusercontent.com/53040514/124583513-526bb200-de7d-11eb-8f5f-103a29de64a8.jpg)
As above. See image

New installation of termux with only termux-setup-storage run and command cut and paste from the Github page with no errors.

**Comment by SaicharanKandukuri** [comment]
you are running it from hippo 
`hippo startvnc` is intended to run before executing `hippo`

and we are planning to change `startvnc` 
so for this time being use `vncserver` command for starting vnc and `vncserver --kill :*` for killing vnc

**Comment by tiptruck** [comment]
Whoops.  Thank you
