### ISSUE TITLE
[vncserver] help

### ISSUE THREAD

**Issue by hdt25** [RandomCoderOrg/ubuntu-on-android#38]
Hi, Your Project is really awesome. 'vncserver' is command used to start vnc server.But there is no command to kill vncserver mentioned by you.After every time I start vnc by vncserver every time display number increases by 1 .I can't connect to vnc directly to my previous configuration. So I every time have to change configuration in vnc app on my phone to connect .Please give a command to kill vnc
![Screenshot_20210723-092315402.jpg](https://user-images.githubusercontent.com/87573085/126735571-f231fbbd-fb5a-4aa7-a860-092dca407717.jpg)

**Comment by SaicharanKandukuri** [comment]
Ok!

**Comment by SaicharanKandukuri** [comment]
Let's say our target port is `:1`
to start vncserver we need to lift Unix sockets(just a couple of files)
for vnc they are stored in `/tmp/.X11-unix`
so do
```bash
vncserver --kill :1
rm -rvf /tmp/.X11-unix/X1
```
or
```bash
vncserver --kill :1
rm -rvf /tmp/.X1-lock
```
or do both
```bash
vncserver --kill :1
rm -rvf /tmp/.X11-unix/X1
rm -rvf /tmp/.X1-lock
```
Then start vncserver
```bash
vncserver :1
```
Done!
<hr>

and shorcut script like `startvnc` and `stopvnc` are in devolopment

**Comment by hdt25** [comment]
Thanks Worked well
So don't have to change port everytime in vnc viewer app

**Comment by SaicharanKandukuri** [comment]
Yep!

**Comment by SaicharanKandukuri** [comment]
> if you found it helpful and working make sure you join our discord server https://discord.gg/u7KDGUc3Aw and close this issue

![ThumbsUpOkayGIF](https://user-images.githubusercontent.com/68287637/126751726-589407bb-ff21-43f9-8dba-6e193a723cb2.gif)
