### ISSUE TITLE
Wallpaper Not Show Up

### ISSUE THREAD

**Issue by dinaradenis** [RandomCoderOrg/ubuntu-on-android#40]
Hi, I Just Installed This And Find The Wallpaper Not Show Up, How Can I Do?
![Screenshot_20210727-144859](https://user-images.githubusercontent.com/62831800/127117130-ae23ab4f-eb2c-4bf2-854c-aa78529b135c.png)
![Screenshot_20210727-144937](https://user-images.githubusercontent.com/62831800/127117228-10f8be03-4e07-40cc-9f38-4f53029fb3f1.png)

**Comment by SaicharanKandukuri** [comment]
try 
```bash
gsettings set org.gnome.settings-daemon.plugins.background active true
```
or
```
xfce4-panel -r
```

**Comment by SaicharanKandukuri** [comment]
sometimes it takes time to load wallpaper

**Comment by dinaradenis** [comment]
Ok, Thanks

**Comment by dinaradenis** [comment]
Oh, I Almost Forget, How I Run Snap? I Search Over An Hour On Google And Not Find A Solution

**Comment by SaicharanKandukuri** [comment]
@dinaradenis running snap is not possible now cause the project is set to run on proot
snap is fully written to run with systemd
and systemd never runs until its PID is 1
and it is not implemented like that in android

snap developers are not interested even to write it for chroot

**Comment by SaicharanKandukuri** [comment]
so it's like impossible to run `snap` in android for now!

**Comment by dinaradenis** [comment]
Ah, I See, Ok I Will Download My Apps From Browser, BTW Thanks!

**Comment by SaicharanKandukuri** [comment]
You are welcome

**Comment by dinaradenis** [comment]
Oh, 1 More Thing, How I Can Update The Desktop Enviroment?

**Comment by SaicharanKandukuri** [comment]
in Linux, everything thing gets upgraded with `apt upgrade`
if it's a layout update from us then I post scripts for it

**Comment by dinaradenis** [comment]
Ok Thanks
