### ISSUE TITLE
Problem audio

### ISSUE THREAD

**Issue by Charlin-Lopes** [RandomCoderOrg/ubuntu-on-android#41]
Hello Friend.  good work.  I'm having difficulties activating the system's audio.  is not catching and when I use the command line of this message.  how should I proceed?
![Screenshot_20210805-015242_Termux](https://user-images.githubusercontent.com/22176481/128293099-52f4829a-ff6f-4db6-8706-1d60b3eb8de1.jpg)

**Comment by SaicharanKandukuri** [comment]
@Charlin-Lopes That commad supposed to be ran outside of hippo
# steps to solve:
- start a new termux session and run it
Or.
- use command `hippo`
- - Which does the job of starting (pulse server) 
<hr>

thanks for the compliment
