### ISSUE TITLE
Change Desktop Environment

### ISSUE THREAD

**Issue by TheUnknownPeople-user** [RandomCoderOrg/ubuntu-on-android#44]
Is it possible to change Xfce to another environment such as Gnome/Mate and others

**Comment by SaicharanKandukuri** [comment]
Yes you can change to other dekstop environment
But GNOME and MATE are considered heavy to run in proot

**Comment by TheUnknownPeople-user** [comment]
> Yes you can change to other dekstop environment
> But GNOME and MATE are considered heavy to run in proot

Ok thanks for the info
