### ISSUE TITLE
Openbox WM distribution becuase xfce4 is heavy

### ISSUE THREAD

**Issue by ghost** [RandomCoderOrg/ubuntu-on-android#46]
**Is your feature request related to a problem? Please describe.**

Downloading 1.7 GB on slow network is difficult. I came to know that Openbox can be used in alternative to xfce4

**Describe the solution you'd like**
One more separate distribution Openbox preinstalled similar to xfce4

**Describe alternatives you've considered**
No alternative

**Additional context**
Thanks

**Comment by SaicharanKandukuri** [comment]
> One more separate distribution Openbox preinstalled similar to xfce4

sure i start working on openbox :+1:

**Comment by ghost** [comment]
Thanks,

Can you make a video for this 
https://github.com/RandomCoderOrg/ubuntu-on-android/wiki/commands-took-to-make-a-custom-rootfs
from scratch?

It will help in creating rootfs locally. Thanks again.

**Comment by SaicharanKandukuri** [comment]
this wont happen for now

> need more contributors

**Comment by Trass3r** [comment]
> Downloading 1.7 GB on slow network is difficult.

I noticed firefox and gimp being installed by default. The image should really be slimmed down.

**Comment by ghost** [comment]
> > Downloading 1.7 GB on slow network is difficult.
> 
> I noticed firefox and gimp being installed by default. The image should really be slimmed down.

firefox and gimp are under 200mb (after installing a window manager/desktop environment). both was supposed to be main component

**Comment by Trass3r** [comment]
Why would you ever use those inside a proot inside termux inside Android?
Thunderbird is also installed. It's just bloat.

**Comment by SaicharanKandukuri** [comment]
@Trass3r 
v2 is not optimized in terms of apps
it just planned to be a better prebuilt tarball build for proot with a good look

a lite version with just xfce4 core and basic Linux utils is already planned
> and thunderbird just came under `xubuntu-desktop` package so it's not bloatware 👌
