### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by tanu771** [RandomCoderOrg/ubuntu-on-android#48]
Extracting rootfs, please wait... stuck

Device - oneplus 7 pro

![Screenshot_20210827-024449](https://user-images.githubusercontent.com/65997207/131037082-7d73f3c4-1cc1-4420-9218-9f6a7e30e0af.jpg)

**Comment by SaicharanKandukuri** [comment]
@tanu771
proot takes a lot of time to make things happen ( proot is slower than native)

####  possible fixes
- leave it for some time
- if you think it really got frozen then kill the session and restart installation **After [acquiring wave-lock](https://wiki.termux.com/wiki/Termux-wake-lock)**
