### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by TheUnknownPeople-user** [RandomCoderOrg/ubuntu-on-android#50]
How To Make Ubuntu Not Too Lag, And How To Remove Games On Ubuntu?

**Comment by SaicharanKandukuri** [comment]
see

**Comment by TheUnknownPeople-user** [comment]
> see

I can't take screenshots or recordings because it's so laggy

**Comment by SaicharanKandukuri** [comment]
https://github.com/RandomCoderOrg/ubuntu-on-android/wiki/XWayland-in-proot
This one works

**Comment by TheUnknownPeople-user** [comment]
emm Ok I'll try it
