### ISSUE TITLE
vgpu while kepping gl4es support

### ISSUE THREAD

**Issue by abasgames** [RandomCoderOrg/ubuntu-on-android#51]
**Is your feature request related to a problem? Please describe.**
i think

**Describe the solution you'd like**
include vgpu support and let users choose between gl4es and vgpu
see https://github.com/luo9674/VGPU it has Most of the GL2.x API and a small amount of GL3.x API(mainly texture and Uniform,
**Describe alternatives you've considered**

**Additional context**
vgpu readme
The project is a bit like GL4ES, where I want to implement a hardware-accelerated GL converter: when an application calls the GL library, it will be mapped to GLES. In other words, VGPU packages the GLES library as a GL library.

**Comment by SaicharanKandukuri** [comment]
@abasgames I request you to show some methods that make it related to this repository
