### ISSUE TITLE
Precompiled mesa with turnip?

### ISSUE THREAD

**Issue by Quackdoc** [RandomCoderOrg/ubuntu-on-android#60]
**Is your feature request related to a problem? Please describe.**
Mesa is dreadfully slow to compile if it manages to complete, and a hassle to even setup in the first place.

**Describe the solution you'd like**
Precompiled binaries I think would be the optimal solution.

**Describe alternatives you've considered**
At least a script that will preform the install, so people can do a set and forget over night, or throughout the day

**Comment by SaicharanKandukuri** [comment]
> Precompiled binaries I think would be the optimal solution.

yes it is an optimal solution but it needs figuring out many things and that static binary may not work optimally

>  script that will perform the install

for now, KGSL powered turnip + zink drivers have only supported selected devices which snapdragon SOC's and I cant produce scripts cause I don't have a device to test.

**Comment by Quackdoc** [comment]
> > Precompiled binaries I think would be the optimal solution.
> 
> yes it is an optimal solution but it needs figuring out many things and that static binary may not work optimally


Just looked at the commit history for https://github.com/Heasterian/mesa

Looks like it just adds a missing header, and disables timeline_semaphore, Likely both just upstream bugs, assuming they get fixed, it should build and work with upstream. and if enabled in the distro, not need a custom install. I am unsure if they have been reported and have issues for them.

but for now, I am at least willing to run scripts overnight.

**Comment by SaicharanKandukuri** [comment]
Ok! I look forward into writing that scripts

**Comment by Quackdoc** [comment]
Im not seemingly able to compile mesa, I am getting missing drm.h despite libdrm and libdrm-dev being installed.

**Comment by SaicharanKandukuri** [comment]
Use `apt-file`
`apt-file search drm.h`

**Comment by Quackdoc** [comment]
yup, I have libdrm-dev installed. still cannot find it. and it does provide it, but so do plenty of other packages.

**Comment by ghost** [comment]
your device supports drm?, same issue with my older device cause it does not supports drm and ended up lefting mesa.

this with newer device:- (drm supported)
![Screenshot_2021-10-08-23-26-45-83_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/65938569/136601791-371601f0-8ed6-4d9c-9364-dc049b5ee441.jpg)
if that file don't exists means you can't compile further

**Comment by Quackdoc** [comment]
Yup, it exists. running an s9+ with snapdragon, so turnip should work on it.

Im also having the same issue trying to compile upstream mesa. possibly a bug with it. Ill tinker with it a bit more before making a bugreport upstream.

**Comment by ghost** [comment]
not sure...

same does with older device (Redmi note 8 pro), issue been fixed in this device (oppo a74). 

let me check it again

**Comment by Quackdoc** [comment]
> not sure...
> 
> same does with older device (Redmi note 8 pro), issue been fixed in this device (oppo a74).
> 
> let me check it again

the redmi is a mali GPU, so I wonder if that could be the cause on that end. I wonder if it is related to android version, I am on Android 10, unfortunately I don't have any other devices to check with. 

Can someone supply a precompiled binary that i can install and test see if it works? unfortunately I cannot do so my self at the moment

**Comment by Quackdoc** [comment]
Ive finally created an issue in the mesa issue tracker here.

[https://gitlab.freedesktop.org/mesa/mesa/-/issues/5476](url)

**Comment by Quackdoc** [comment]
Grima04's mesa seems to build on my device. i will look into it some more. but I suspect it's because he flatout removes libdrm. but it is odd that libdrm would be incompatible

**Comment by Quackdoc** [comment]
@GxmerSam  any chance you could dump the output of your meson config? just want to compare if some dependencies are missing

**Comment by Quackdoc** [comment]
Turns out I need to cp -rn /usr/include/drm/* /usr/include/

**Comment by SaicharanKandukuri** [comment]
@Quackdoc for now providing scripts for mesa or turnip is out of this repo scope
cause they are vendor-specific and may need root for implementing in some cases
but here is a script from @Heasterian 
```bash
sudo apt build-dep mesa -y \
sudo apt install git -y \
 git clone https://github.com/Heasterian/mesa \
 cd mesa \
 meson build -D platforms=x11,wayland -D gallium-drivers=swrast,zink -D vulkan-drivers=freedreno -D dri3=enabled  -D egl=enabled  -D gles2=enabled -D glvnd=true -D glx=dri  -D libunwind=disabled -D shared-glapi=enabled -D microsoft-clc=disabled  -D valgrind=disabled  -D gles1=disabled -D freedreno-kgsl=true -Dgallium-nine=true \
 ninja -C build \
 sudo ninja -C build install
```

Thank you for making an issue

**Comment by Quackdoc** [comment]
Ill close the issue with this appendage incase anyone comes across this with my issue, if anyone eas wondering, the "fix" for my issue was to copy the drm files directly into its parent folder include.

**Comment by kubawis128** [comment]
Hi i tried this on my Xiaomi Redmi Note 8T (Adreno 610,Custom ROM(Android 12 Arrow OS with kernel 4.14)) and the Mesa driver compiled without the issue(after moving drm.h file) but when i try to run something that needs vulkan (vulkaninfo, vkcube,zink) i get segfault by libvulkan.so
Output from gdb(vkcube):
```
Thread 1 "vkcube" received signal SIGSEGV, Segmentation fault.
tu_physical_device_init (device=device@entry=0x300025f3e0, instance=instance@entry=0x300025f1a0) at ../src/freedreno/vulkan/tu_device.c:212
212	   if (strncmp(fd_name, "FD", 2) == 0) {
```
gdb(vulkaninfo):
```
Thread 1 "vulkaninfo" received signal SIGSEGV, Segmentation fault.
0x0000007fbefcf6d8 in ?? () from /lib/aarch64-linux-gnu/libvulkan.so
```
and opengl works fine on llvmpipe

**Comment by Quackdoc** [comment]
> Hi i tried this on my Xiaomi Redmi Note 8T (Adreno 610,Custom ROM(Android 12 Arrow OS with kernel 4.14)) and the Mesa driver compiled without the issue(after moving drm.h file) but when i try to run something that needs vulkan (vulkaninfo, vkcube,zink) i get segfault by libvulkan.so Output from gdb(vkcube):
> 
> ```
> Thread 1 "vkcube" received signal SIGSEGV, Segmentation fault.
> tu_physical_device_init (device=device@entry=0x300025f3e0, instance=instance@entry=0x300025f1a0) at ../src/freedreno/vulkan/tu_device.c:212
> 212	   if (strncmp(fd_name, "FD", 2) == 0) {
> ```
> 
> gdb(vulkaninfo):
> 
> ```
> Thread 1 "vulkaninfo" received signal SIGSEGV, Segmentation fault.
> 0x0000007fbefcf6d8 in ?? () from /lib/aarch64-linux-gnu/libvulkan.so
> ```
> 
> and opengl works fine on llvmpipe

This would be something to report upstream on the mesa gitlab

**Comment by kubawis128** [comment]
Maybe i should compile upstream mesa and try it because before i used [this version of mesa](https://github.com/Heasterian/mesa) as recommended before.

This is what i used:
> ```shell
> sudo apt build-dep mesa -y \
> sudo apt install git -y \
>  git clone https://github.com/Heasterian/mesa \
>  cd mesa \
>  meson build -D platforms=x11,wayland -D gallium-drivers=swrast,zink -D vulkan-drivers=freedreno -D dri3=enabled  -D egl=enabled  -D gles2=enabled -D glvnd=true -D glx=dri  -D libunwind=disabled -D shared-glapi=enabled -D microsoft-clc=disabled  -D valgrind=disabled  -D gles1=disabled -D freedreno-kgsl=true -Dgallium-nine=true \
>  ninja -C build \
>  sudo ninja -C build install
> ```

**Comment by kubawis128** [comment]
Latest version of mesa and others(21.0 and 20.3) falied to compile
[Build log latest](https://pastebin.com/LapHDYLm)
[Build log 21.0](https://pastebin.com/98WubQJF)
[Build log 20.3](https://pastebin.com/uF6pe4Ff)
All of them seem to have similar error like:
```
../src/freedreno/vulkan/msm_kgsl.h:487:14: error: expected ':', ',', ';', '}' or '__attribute__' before '*' token
  487 |  void __user *value;
```
or
```
../src/freedreno/vulkan/tu_kgsl.c:116:8: error: 'struct kgsl_gpuobj_import' has no member named 'priv'
  116 |       .priv = (uintptr_t)&import_dmabuf,
      |        ^~~~
```

**Comment by SaicharanKandukuri** [comment]
create an issue in mesa

**Comment by kubawis128** [comment]
[done](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5644)

**Comment by Saikatsaha1996** [comment]
> 

Can you help please?

![Screenshot_2022-07-01-08-40-22-888_tech ula](https://user-images.githubusercontent.com/72664192/176816052-47058602-d63b-409d-b987-f4cd438d2272.jpg)
