### ISSUE TITLE
Viewing(vnc) on other device

### ISSUE THREAD

**Issue by AnD418** [RandomCoderOrg/ubuntu-on-android#68]
I want to use another device as it's display. I have tried in anronix's version and it worked perfectly. I know someone already raised an issue but that doesn't seem to work.
Please help.

**Comment by SaicharanKandukuri** [comment]
it should work
only works within local networks

**Comment by AnD418** [comment]
I know it should but it doesn't. And i am on a local network. Here are the screenshots. 
![Screenshot_20211029-070406](https://user-images.githubusercontent.com/69518879/139358968-9e5d8067-092d-405b-8b44-a3e61d0b43ee.png)
![Screenshot_20211029-070415](https://user-images.githubusercontent.com/69518879/139358975-58989aa5-0f58-4576-a5f9-675ae571e3c4.png)
![Screenshot_20211029_070345_com termux](https://user-images.githubusercontent.com/69518879/139358977-5df0bba6-59c3-4384-b343-09e8ce7ce71e.jpg)

**Comment by ghost** [comment]
It works, already did with phone-to-netbook

First start vncserver with
```
tigervncserver -geometry 1366x768 -localhost no -xstartup /usr/bin/xfce4-session -listen tcp :1
```
Then start hotspot, connect to another device and  then `Ipaddress:port`.

**Comment by AnD418** [comment]
It worked. Thanks
