### ISSUE TITLE
Please can you add new apps 

### ISSUE THREAD

**Issue by Andre-cmd-rgb** [RandomCoderOrg/ubuntu-on-android#7]
Can you add apps and an updater of all entire system

**Comment by SaicharanKandukuri** [comment]
Apps & Updaters??
Can you be more specific?

**Comment by Andre-cmd-rgb** [comment]
An updater that will update the system without have to re clone the repository

**Comment by SaicharanKandukuri** [comment]
Yep I am working on it
By the next next release include 
-  A one-line installer
-  upgrade patching scripts/system (works automatic and manual)
-  And libGL support for xserver xsdl (Testing)

**Comment by SaicharanKandukuri** [comment]
Hope I got what you are asking for

**Comment by Andre-cmd-rgb** [comment]
yes thanks

**Comment by Andre-cmd-rgb** [comment]
Can you add this 
`
#setting up audio
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
#logging in
proot-distro login hippo`

**Comment by SaicharanKandukuri** [comment]
where?

**Comment by Andre-cmd-rgb** [comment]
So it's faster to start everything

**Comment by SaicharanKandukuri** [comment]
Oh! I got you now 
I've made a file at ["/etc/scripts/hippo"](https://github.com/RandomCoderOrg/ubuntu-on-android/blob/modified/etc/scripts/hippo) which goes as a shortcut after new release to launch quickly 

You can make a Pull-Request by modifying that file from your FORK cause you gave an idea with its code👍

**Comment by Andre-cmd-rgb** [comment]
When will exit the next update

**Comment by SaicharanKandukuri** [comment]
In 5 - 8 days

**Comment by Andre-cmd-rgb** [comment]
Thanks

**Comment by Andre-cmd-rgb** [comment]
Can you make all entyre System faster and smoother

**Comment by SaicharanKandukuri** [comment]
can you say in detail

**Comment by SaicharanKandukuri** [comment]
This issue is multi topic and Going well and long
> Converting to discussion
