### ISSUE TITLE
App

### ISSUE THREAD

**Issue by chau2313** [RandomCoderOrg/ubuntu-on-android#70]
https://github.com/chau2313/opensource.guide

**Comment by GxmerSam** [comment]
so what's this actually?

**Comment by SaicharanKandukuri** [comment]
@chau2313 are you willing to contribute something?
Or suggestions?
Or just trying issues button!

**Comment by SaicharanKandukuri** [comment]
@chau2313 check this out https://youtu.be/TJlYiMp8FuY
& for now this issue is invalid (2/3)
