### ISSUE TITLE
Vscode and sublime text not installed

### ISSUE THREAD

**Issue by Erik-VT** [RandomCoderOrg/ubuntu-on-android#73]
Is vscode and sublime still included in installation?
Neither are installed in udroid, but at least vscode shown in screenshots. Installation of 1.62.0 of vscode results in segfault.

**Comment by SaicharanKandukuri** [comment]
@Erik-VT vscode gives segfault in `armv8l` devices
& We have to drop support for it! Cause of vscode & most of linux apps not made for `armv8l` except for core application
