### ISSUE TITLE
[ Optimization IDEA ]: Move all media content to other place

### ISSUE THREAD

**Issue by AnninoDr4** [RandomCoderOrg/ubuntu-on-android#76]
found that whole repo size is ~32 mega bytes  and media content is alone 16+ mega bytes
we need to move all media content from core repositories (i.e like `ubuntu-on-android` & `fs-manager-udroid` which users device clone during installation) and bind them to repos with hyperlinks

so i need ideas
@GxmerSam 
@SaicharanKandukuri

**Comment by ghost** [comment]
16mb isn't a big deal. but useless while cloning, maybe a new repository for storing the media or need to host images somewhere like gfycat or Imgur

**Comment by SaicharanKandukuri** [comment]
lets choose imgur

**Comment by SaicharanKandukuri** [comment]
i'll start working on this

**Comment by AnninoDr4** [comment]
wait @SaicharanKandukuri  what if imgur server goes down
better use git repo like `udroid-media` or something similar

**Comment by SaicharanKandukuri** [comment]
ya, it's a rare case but it may happen too!

`udroid-media` repo

media content from all repos related to udroid goes there!
