### ISSUE TITLE
Udroid not installing

### ISSUE THREAD

**Issue by TOXIC-KID** [RandomCoderOrg/ubuntu-on-android#77]
I tried to install udroid and it's doing nothing I leave it for about 5 min and it's keeps showing up the numbers .  
![Screenshot_2021-11-17-14-48-14-03_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/72244019/142172646-2575cd53-359c-4fb8-893b-5070367a4a94.png)

**Comment by SaicharanKandukuri** [comment]
@SOUL-HAKER this may be an issue from your ISP or Github servers
I suggest you waiting sometime & try again

> installer code not-modified so its not a bug from ourside

**Comment by TOXIC-KID** [comment]
> @SOUL-HAKER this may be an issue from your ISP or Github servers I suggest you waiting sometime & try again
> 
> > installer code not-modified so its not a bug from ourside

Yeah I will wait and thanks for your support

**Comment by SaicharanKandukuri** [comment]
![Screenshot_20211117-180823_Termux](https://user-images.githubusercontent.com/68287637/142202139-4a661136-858f-42ce-a2c7-bf1ba94e5a05.jpg)

Looks like termux or GitHub issue for some reason download apps can't receive response!

**Comment by SaicharanKandukuri** [comment]
@SOUL-HAKER looks github servers had some issues
so server tacking long time to respond back for large files

in my tests servers took ~10minutes to respond back & start download stream
so for now start installer and leave it running. 

> usually this kind of problems get fixed in a day

**Comment by TOXIC-KID** [comment]
> @SOUL-HAKER looks github servers had some issues so server tacking long time to respond back for large files
> 
> in my tests servers took ~10minutes to respond back & start download stream so for now start installer and leave it running.
> 
> > usually this kind of problems get fixed in a day

Yeah ok . Thanks for your assistance
