### ISSUE TITLE
Update to Ubuntu 21.10

### ISSUE THREAD

**Issue by archisman-panigrahi** [RandomCoderOrg/ubuntu-on-android#79]
**Is your feature request related to a problem? Please describe.**
Ubuntu 21.10 has been released, and 21.04 will reach end of life in January.

**Describe the solution you'd like**
Please update the project to Ubuntu 21.10

**Comment by SaicharanKandukuri** [comment]
sure it's already on wheels may be in week or so👍

**Comment by SaicharanKandukuri** [comment]
`termux-x11` brought new things to take care of, may take more time

**Comment by heduardoaa** [comment]
hi!! I have a question, does this update affect my data stored in the current 21.04 distro?

**Comment by SaicharanKandukuri** [comment]
for now we can't follow traditional upgrade systems cause platform is Android proot

> But we have other ways for upgrading to 21.10 without dataloss ( it's not  guaranteed by the way ) & we release it soon after V3
> > Cause that way is pretty much unstable
