### ISSUE TITLE
[VNC]: failed to start vnc after removing plank

### ISSUE THREAD

**Issue by mosayeb2543** [RandomCoderOrg/ubuntu-on-android#81]
After i quite the plank vnc get stop and after i unistall plank vnc no run anymore 
Some panel profile no get work and make full of bug and it need restart phone but the udroid no work until reinstall it.

**Comment by SaicharanKandukuri** [comment]
edit vnc config file `~/.vnc/xstartup`
comment or remove the line which looks like `plank &`

**Comment by mosayeb2543** [comment]
Ok thanks

**Comment by mosayeb2543** [comment]
After remove plank from xstartup vncserver didnt able to ruun

**Comment by SaicharanKandukuri** [comment]
`cat ~/.vnc/*5901.log` could help to know what problem is!

**Comment by mosayeb2543** [comment]
It gona be hard i find another way for trun off it so it is good too

**Comment by SaicharanKandukuri** [comment]
> make sure you removed `&` from last line
or 

try this script

```bash
#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export PULSE_SERVER=127.0.0.1
dbus-launch --exit-with-session startxfce4
```

**Comment by SaicharanKandukuri** [comment]
This issue is fixed!
