### ISSUE TITLE
Termux keeps force closing all sessions after starting vnc on Ubuntu

### ISSUE THREAD

**Issue by elfametesar** [RandomCoderOrg/ubuntu-on-android#83]
![Screenshot_20211201-040440_Termux](https://user-images.githubusercontent.com/58091473/144152921-b4bfccc1-3fd6-4911-b8c0-6acac5bcdd76.png)

**Comment by SaicharanKandukuri** [comment]
try `termux-wakelock`
https://wiki.termux.com/wiki/Termux-wake-lock

**Comment by elfametesar** [comment]
> try `termux-wakelock` https://wiki.termux.com/wiki/Termux-wake-lock

it still happens no matter what, it seems to happen when I start VNC server with xfce4, otherwise it doesn't force close. by the way I think I understand why you taught wake lock might help but this issue happens in under 1 minute after the start and regardless if I leave termux in the background or not

**Comment by SaicharanKandukuri** [comment]
Probably some kind of battery management system killed process!

**Comment by stopka-html** [comment]
If this was due to energy conservation, the thermux would be completely shut down and restarted without saving

**Comment by elfametesar** [comment]
> If this was due to energy conservation, the thermux would be completely shut down and restarted without saving

Why would it be shut down for energy conservation while I am still on the app, while the app isn't even in the background? I mean battery management makes sense and don't make sense at the same time

Edit: Ahahah it even crashes MT Manager terminal

**Comment by SaicharanKandukuri** [comment]
> If this was due to energy conservation, the thermux would be completely shut down and restarted without saving

Can't say that's sure! Cause termux exited with signal 9 `SIGKILL` and different vendors implementations use different ways for killing overhead processes!

**Comment by stopka-html** [comment]
I have a problem that the thermux in the background turns off during heavy work did not help any settings (

**Comment by SaicharanKandukuri** [comment]
Tried termux-wayland?
https://dev.to/saicharankandukuri/xwayland-in-proot-3ho

**Comment by stopka-html** [comment]
![Screenshot_2021-12-01-12-09-03-447_com.termux.jpg](https://user-images.githubusercontent.com/85645977/144224250-8d2f69ac-7da8-4283-869e-041b96328b5e.jpg)
Error

**Comment by SaicharanKandukuri** [comment]
Ah!  you are using the termux fdroid version
