### ISSUE TITLE
Please make a light version of it

### ISSUE THREAD

**Issue by PiyushYadav007** [RandomCoderOrg/ubuntu-on-android#85]
There are too many softwares in this version I mean it's good but I wanted a lighter version of that which contains only necessary softwares and of smaller size. Please

**Comment by SaicharanKandukuri** [comment]
sure!

**Comment by SaicharanKandukuri** [comment]
> sure!

ya that's how it works when things get easy!

**Comment by PiyushYadav007** [comment]
You create it?

**Comment by SaicharanKandukuri** [comment]
yep! with some help

**Comment by PiyushYadav007** [comment]
Then please publish it. I have a work to do

**Comment by SaicharanKandukuri** [comment]
it so much in dev stage & may break things

**Comment by SaicharanKandukuri** [comment]
https://github.com/RandomCoderOrg/fs-cook

**Comment by PiyushYadav007** [comment]
Ok it ubuntu right?

**Comment by SaicharanKandukuri** [comment]
Yep!

[ see this ](https://github.com/RandomCoderOrg/fs-cook/wiki/fs-cook)

**Comment by PiyushYadav007** [comment]
How to install this?

**Comment by SaicharanKandukuri** [comment]
Just clone & execute build scripts

**Comment by PiyushYadav007** [comment]
Setup.sh

**Comment by PiyushYadav007** [comment]
Right

**Comment by PiyushYadav007** [comment]
Or cook.sh

**Comment by SaicharanKandukuri** [comment]
@WhiteHacker993 

also check this release docs https://github.com/RandomCoderOrg/fs-cook/releases/tag/v1.0

> but remember **fs-cook** Is still in the development stage & need to uncover a lot of variables and fix code to do it like `build-udroid.sh` & you get fresh built udroid tarball with your config
