### ISSUE TITLE
Can i install Clion on it?

### ISSUE THREAD

**Issue by GZhengHao** [RandomCoderOrg/ubuntu-on-android#86]
I've tried but i coudn't operate any file downloaded from theire site(even delete it), it aways says "no such file or directory" , I did a bit search but still couldn't solve the problem, looks like it is due to the different architecture? 
Just want to know if it is possible to install clion.  thanks !  : )

**Comment by SaicharanKandukuri** [comment]
![Screenshot_20211204-180251_NetHunter KeX](https://user-images.githubusercontent.com/68287637/144709497-1a2db787-8e0c-46cc-b8eb-f426aa847dce.jpg)

Yes!

**Comment by GZhengHao** [comment]
Thats so cool！ How did you do it？

**Comment by SaicharanKandukuri** [comment]
just

> download from this webpage: https://www.jetbrains.com/clion/download/download-thanks.html?platform=linux

or
```bash
axel https://download.jetbrains.com/cpp/CLion-2021.3.tar.gz
tar -xf CLion-2021.3.tar.gz
```

then

```bash
cd cl*/bin
bash clion.sh
```
