### ISSUE TITLE
Xwayland

### ISSUE THREAD

**Issue by stopka-html** [RandomCoderOrg/ubuntu-on-android#87]
![Screenshot_2021-12-03-09-05-05-668_com termux](https://user-images.githubusercontent.com/85645977/144567512-7075ab40-dafa-48dc-8207-1449e6d68af1.jpg)
at startup:termux-x11

**Comment by SaicharanKandukuri** [comment]
Check for termux-dev

**Comment by SaicharanKandukuri** [comment]
![Screenshot_20211203-141418_Termux](https://user-images.githubusercontent.com/68287637/144573233-97c4c534-1aa8-4443-8710-8145e92fe07f.jpg)
![Screenshot_20211203-141425_Termux](https://user-images.githubusercontent.com/68287637/144573241-b946b677-cd50-4ef1-ba67-02e672911e1f.jpg)
![Screenshot_20211203-141429_Termux](https://user-images.githubusercontent.com/68287637/144573244-945574b0-58d2-4bb4-b619-ca6c742da645.jpg)

**Comment by SaicharanKandukuri** [comment]
For now termux Xwayland only work with GITHUB BUILDS

**Comment by stopka-html** [comment]
![Screenshot_2021-12-03-09-53-32-547_com.termux.jpg](https://user-images.githubusercontent.com/85645977/144573924-3b6a7424-3270-406e-a0aa-06b20ff96132.jpg)

**Comment by stopka-html** [comment]
I think

**Comment by stopka-html** [comment]
but i installed the githab version

**Comment by SaicharanKandukuri** [comment]
Or try manuall way
like
```bash
pkg install xwayland
```
Open termux-x11 app
& do 
```bash
export XDG_RUNTIME_DIR=$TMPDIR
Xwayland :0 > /dev/null &
proot-distro login udroid --shared-tmp
```

then start your DE
```

**Comment by stopka-html** [comment]
![Screenshot_2021-12-03-11-31-29-127_com.termux.jpg](https://user-images.githubusercontent.com/85645977/144587997-d99ae62d-8958-4c6c-871d-eb4a5caecc34.jpg)

**Comment by SaicharanKandukuri** [comment]
@stopka-html 

probably you started termux-x11 app before starting termux app?

If you did it correct way you should have wayalnd lock & socket file `$TMPDIR`

![Screenshot_20211203-172554_Termux](https://user-images.githubusercontent.com/68287637/144598607-8041b369-0c71-42ac-89c1-f62f54699aad.jpg)

**Comment by stopka-html** [comment]
decision:
```
nano ~/.termux/termux.properties
```

and just uncomment 
```
allow-external-apps = true
```
