### ISSUE TITLE
Environment Error

### ISSUE THREAD

**Issue by CassieBtw** [RandomCoderOrg/ubuntu-on-android#88]
I installed 'termux-prefix-switcher' for no purpose then I revert it back. I tried reinstalling using 'udroid' command, this error appears. I don't know how to solve this.

![Screenshot_2021-12-09-20-32-41-85](https://user-images.githubusercontent.com/83238487/145397502-8d68e068-a7e5-4925-808c-9eaf56525bf2.png)

**Comment by SaicharanKandukuri** [comment]
found the issue
https://github.com/RandomCoderOrg/fs-manager-udroid/commit/7423ed31a91b611fd6f150bf334f342f41319f9a#diff-974d1cc4fd992769d42bb6d169faac68933c08089b21d60bd465732544c782a3L69

**Comment by SaicharanKandukuri** [comment]
@CassieBtw 

this bug is fixed now [commit](https://github.com/RandomCoderOrg/fs-manager-udroid/commit/7bacf04eaa3a679886fda94567e48739e76b31f8)

you could fix it with either manually cloning or just do this
```
sed -i '278s/__verify_bin_path/#/' ../usr/bin/bash
```

> this bug was created 3 hours ago Thanks for noticing us! 👍

**Comment by ke8lne** [comment]
> @CassieBtw
> 
> this bug is fixed now [commit](https://github.com/RandomCoderOrg/fs-manager-udroid/commit/7bacf04eaa3a679886fda94567e48739e76b31f8)
> 
> you could fix it with either manually cloning or just do this
> 
> ```
> sed -i '278s/__verify_bin_path/#/' ../usr/bin/bash
> ```
> 
> > this bug was created 3 hours ago Thanks for noticing us! 👍

A'ight, thanks for your response. 👍🏻
