### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by fxmirnet** [RandomCoderOrg/ubuntu-on-android#91]
[*] Installing udroid...
[*] Using cached rootfs tarball...
[*] Checking integrity, please wait...
[*] Extracting rootfs, please wait...
CANNOT LINK EXECUTABLE "tar": library "libandroid-glob.so" not found
[*] Writing '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/udroid/etc/profile'...
find: ‘usr/lib/’: No such file or directory

**Comment by SaicharanKandukuri** [comment]
@fxmirnet 
please provide output of `termux-info`

**Comment by fxmirnet** [comment]
~ $ termux-info
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main stable main
# game-repo (sources.list.d/game.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/game-packages-24/ games stable
# science-repo (sources.list.d/science.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/science-packages-24/ science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Thu Nov 18 14:55:51 CST 2021 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
ELS-AN00

**Comment by SaicharanKandukuri** [comment]
@fxmirnet may be a device-specific issue
cause this issue is not common in the termux app & in this project

> try in another device
