### ISSUE TITLE
Set keyboard layout

### ISSUE THREAD

**Issue by JohnRDOrazio** [RandomCoderOrg/ubuntu-on-android#93]
How can I detect or set the correct keyboard layout? I have tried `dpkg-reconfigure keyboard-configuration`, I have chosen the Italian keyboard layout, but it doesn't seem to take effect. Is it perhaps necessary to restart a proot process, to reboot Ubuntu?

If I try to access "keyboard layout" from the graphical Ubuntu settings, and I set Italian layout from there, it still seems not to make a difference.

If I try to access "language and region" I get an error.

**Comment by SaicharanKandukuri** [comment]
@JohnRDOrazio keyboard layout & languages depend on termux( in CLI ) & vnc apps (when accessing display) 
that means termux app developers or vnc server app developers should add those languages & support different layouts so that udroid could receive keys

**Comment by nathaneltitane** [comment]
> How can I detect or set the correct keyboard layout? I have tried `dpkg-reconfigure keyboard-configuration`, I have chosen the Italian keyboard layout, but it doesn't seem to take effect. Is it perhaps necessary to restart a proot process, to reboot Ubuntu?
> 
> If I try to access "keyboard layout" from the graphical Ubuntu settings, and I set Italian layout from there, it still seems not to make a difference.
> 
> If I try to access "language and region" I get an error.

if this is ubuntu, 'sudo dpkg-reconfigure keyboard-configuration' should do it.
tested on my own setup.

even setting language on vnc fails due to some issues with transmission protocols.

**Comment by SaicharanKandukuri** [comment]
@JohnRDOrazio 
You should use RealVnc app for multi language. Keyboard layout detection or changing it is not possible in proot( which udroid works on )
So `dpkg-reconfigure keyboard-configuration` is not an option here! 
 keyboard layouts & languages are detected & managed android itself and it's sanitized enough.


So if app supports the language you choose then you can continue
![Screenshot_20220103-230346_VNC Viewer](https://user-images.githubusercontent.com/68287637/147962028-9d2200b2-af62-4e6d-814e-87a66daf244f.jpg)

> Termux app dev builds won't support kana input but you could use it in RealVnc app Cause it do have support to take kana ( japnese alphabets )

So keyboard layout depends on app you using & keyboard you're using

**Comment by SaicharanKandukuri** [comment]
> If I try to access "keyboard layout" from the graphical Ubuntu settings, and I set Italian layout from there, it still seems not to make a difference.

> If I try to access "language and region" I get an error.

Changing keyboard layout involves updating init inside ubuntu!

& Keyboard input are recived by android so using that command won't do anything in Ubuntu GUI
 
> Using an app that support languages is an option

You don't need it in any android proot based linux

**Comment by nathaneltitane** [comment]
> > If I try to access "keyboard layout" from the graphical Ubuntu settings, and I set Italian layout from there, it still seems not to make a difference.
> 
> > If I try to access "language and region" I get an error.
> 
> Changing keyboard layout involves updating init inside ubuntu!
> 
> & Keyboard input are recived by android so using that command won't do anything in Ubuntu GUI
>  
> > Using an app that support languages is an option
> 
> You don't need it in any android proot based linux

@SaicharanKandukuri  so what you mean is that the change in input method is done through Android, using the builtins from the VNC applications we use?

**Comment by SaicharanKandukuri** [comment]
> > > If I try to access "keyboard layout" from the graphical Ubuntu settings, and I set Italian layout from there, it still seems not to make a difference.
> > 
> > 
> > > If I try to access "language and region" I get an error.
> > 
> > 
> > Changing keyboard layout involves updating init inside ubuntu!
> > & Keyboard input are recived by android so using that command won't do anything in Ubuntu GUI
> > > Using an app that support languages is an option
> > 
> > 
> > You don't need it in any android proot based linux
> 
> @SaicharanKandukuri so what you mean is that the change in input method is done through Android, using the builtins from the VNC applications we use?

@nathaneltitane 
based on my research Yes!

**Comment by JohnRDOrazio** [comment]
Ok I succeeded in using an Italian keyboard layout by going to the Nvidia Shield Android settings for the "physical" (Bluetooth) keyboard, and setting the Italian language there. After that, all applications (Termux, VNC, Ubuntu) were correctly using the Italian keyboard layout.
