### ISSUE TITLE
Set date and time

### ISSUE THREAD

**Issue by JohnRDOrazio** [RandomCoderOrg/ubuntu-on-android#94]
Is it possible to set the timezone?

From the graphical Ubuntu, if I try to open settings -> date and time, I get an error.

From the terminal, if I type `datetimectl` I get an error that the system was not booted with systemd.

**Comment by SaicharanKandukuri** [comment]
try `dpkg-reconfigure tzdata`
& change timezone!

`datetimectl` won't work in proot

**Comment by JohnRDOrazio** [comment]
Worked! Thank you.
