### ISSUE TITLE
Root access

### ISSUE THREAD

**Issue by somerandomguy404** [RandomCoderOrg/ubuntu-on-android#98]
Every time i start the Ubuntu in termux i become as a root user (superuser) and i don't know how to become a normal user
Dose anyone know how to fix that?

**Comment by SaicharanKandukuri** [comment]
@somerandomguy404 See this discussion
It already answered!
- #97

**Comment by SaicharanKandukuri** [comment]
https://github.com/RandomCoderOrg/ubuntu-on-android/discussions/97#discussioncomment-1907343

**Comment by somerandomguy404** [comment]
Thanks
